#coding=utf8

try:
    from . import xspcomm as xsp
except Exception as e:
    import xspcomm as xsp

if __package__ or "." in __name__:
    from .libUT_FtqPdMem import *
else:
    from libUT_FtqPdMem import *


class DUTFtqPdMem(object):

    # initialize
    def __init__(self, *args, **kwargs):
        self.dut = DutUnifiedBase(*args)
        self.xclock = xsp.XClock(self.dut.simStep)
        self.xport  = xsp.XPort()
        self.xclock.Add(self.xport)
        self.event = self.xclock.getEvent()
        self.internal_signals = {}
        # set output files
        if kwargs.get("waveform_filename"):
            self.dut.SetWaveform(kwargs.get("waveform_filename"))
        if kwargs.get("coverage_filename"):
            self.dut.SetCoverage(kwargs.get("coverage_filename"))

        # all Pins
        self.clock = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.reset = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_ren_0 = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_ren_1 = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_raddr_0 = xsp.XPin(xsp.XData(6, xsp.XData.In), self.event)
        self.io_raddr_1 = xsp.XPin(xsp.XData(6, xsp.XData.In), self.event)
        self.io_rdata_0_brMask_0 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_rdata_0_brMask_1 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_rdata_0_brMask_2 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_rdata_0_brMask_3 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_rdata_0_brMask_4 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_rdata_0_brMask_5 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_rdata_0_brMask_6 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_rdata_0_brMask_7 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_rdata_0_brMask_8 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_rdata_0_brMask_9 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_rdata_0_brMask_10 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_rdata_0_brMask_11 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_rdata_0_brMask_12 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_rdata_0_brMask_13 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_rdata_0_brMask_14 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_rdata_0_brMask_15 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_rdata_0_jmpInfo_valid = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_rdata_0_jmpInfo_bits_0 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_rdata_0_jmpInfo_bits_1 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_rdata_0_jmpInfo_bits_2 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_rdata_0_jmpOffset = xsp.XPin(xsp.XData(4, xsp.XData.Out), self.event)
        self.io_rdata_0_rvcMask_0 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_rdata_0_rvcMask_1 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_rdata_0_rvcMask_2 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_rdata_0_rvcMask_3 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_rdata_0_rvcMask_4 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_rdata_0_rvcMask_5 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_rdata_0_rvcMask_6 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_rdata_0_rvcMask_7 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_rdata_0_rvcMask_8 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_rdata_0_rvcMask_9 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_rdata_0_rvcMask_10 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_rdata_0_rvcMask_11 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_rdata_0_rvcMask_12 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_rdata_0_rvcMask_13 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_rdata_0_rvcMask_14 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_rdata_0_rvcMask_15 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_rdata_1_brMask_0 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_rdata_1_brMask_1 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_rdata_1_brMask_2 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_rdata_1_brMask_3 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_rdata_1_brMask_4 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_rdata_1_brMask_5 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_rdata_1_brMask_6 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_rdata_1_brMask_7 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_rdata_1_brMask_8 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_rdata_1_brMask_9 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_rdata_1_brMask_10 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_rdata_1_brMask_11 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_rdata_1_brMask_12 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_rdata_1_brMask_13 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_rdata_1_brMask_14 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_rdata_1_brMask_15 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_rdata_1_jmpInfo_valid = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_rdata_1_jmpInfo_bits_0 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_rdata_1_jmpInfo_bits_1 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_rdata_1_jmpInfo_bits_2 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_rdata_1_jmpOffset = xsp.XPin(xsp.XData(4, xsp.XData.Out), self.event)
        self.io_rdata_1_jalTarget = xsp.XPin(xsp.XData(50, xsp.XData.Out), self.event)
        self.io_rdata_1_rvcMask_0 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_rdata_1_rvcMask_1 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_rdata_1_rvcMask_2 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_rdata_1_rvcMask_3 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_rdata_1_rvcMask_4 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_rdata_1_rvcMask_5 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_rdata_1_rvcMask_6 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_rdata_1_rvcMask_7 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_rdata_1_rvcMask_8 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_rdata_1_rvcMask_9 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_rdata_1_rvcMask_10 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_rdata_1_rvcMask_11 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_rdata_1_rvcMask_12 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_rdata_1_rvcMask_13 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_rdata_1_rvcMask_14 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_rdata_1_rvcMask_15 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_wen_0 = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_waddr_0 = xsp.XPin(xsp.XData(6, xsp.XData.In), self.event)
        self.io_wdata_0_brMask_0 = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_wdata_0_brMask_1 = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_wdata_0_brMask_2 = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_wdata_0_brMask_3 = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_wdata_0_brMask_4 = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_wdata_0_brMask_5 = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_wdata_0_brMask_6 = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_wdata_0_brMask_7 = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_wdata_0_brMask_8 = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_wdata_0_brMask_9 = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_wdata_0_brMask_10 = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_wdata_0_brMask_11 = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_wdata_0_brMask_12 = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_wdata_0_brMask_13 = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_wdata_0_brMask_14 = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_wdata_0_brMask_15 = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_wdata_0_jmpInfo_valid = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_wdata_0_jmpInfo_bits_0 = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_wdata_0_jmpInfo_bits_1 = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_wdata_0_jmpInfo_bits_2 = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_wdata_0_jmpOffset = xsp.XPin(xsp.XData(4, xsp.XData.In), self.event)
        self.io_wdata_0_jalTarget = xsp.XPin(xsp.XData(50, xsp.XData.In), self.event)
        self.io_wdata_0_rvcMask_0 = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_wdata_0_rvcMask_1 = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_wdata_0_rvcMask_2 = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_wdata_0_rvcMask_3 = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_wdata_0_rvcMask_4 = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_wdata_0_rvcMask_5 = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_wdata_0_rvcMask_6 = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_wdata_0_rvcMask_7 = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_wdata_0_rvcMask_8 = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_wdata_0_rvcMask_9 = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_wdata_0_rvcMask_10 = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_wdata_0_rvcMask_11 = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_wdata_0_rvcMask_12 = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_wdata_0_rvcMask_13 = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_wdata_0_rvcMask_14 = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_wdata_0_rvcMask_15 = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)


        # BindDPI
        self.clock.BindDPIPtr(self.dut.GetDPIHandle("clock", 0), self.dut.GetDPIHandle("clock", 1))
        self.reset.BindDPIPtr(self.dut.GetDPIHandle("reset", 0), self.dut.GetDPIHandle("reset", 1))
        self.io_ren_0.BindDPIPtr(self.dut.GetDPIHandle("io_ren_0", 0), self.dut.GetDPIHandle("io_ren_0", 1))
        self.io_ren_1.BindDPIPtr(self.dut.GetDPIHandle("io_ren_1", 0), self.dut.GetDPIHandle("io_ren_1", 1))
        self.io_raddr_0.BindDPIPtr(self.dut.GetDPIHandle("io_raddr_0", 0), self.dut.GetDPIHandle("io_raddr_0", 1))
        self.io_raddr_1.BindDPIPtr(self.dut.GetDPIHandle("io_raddr_1", 0), self.dut.GetDPIHandle("io_raddr_1", 1))
        self.io_rdata_0_brMask_0.BindDPIPtr(self.dut.GetDPIHandle("io_rdata_0_brMask_0", 0), self.dut.GetDPIHandle("io_rdata_0_brMask_0", 1))
        self.io_rdata_0_brMask_1.BindDPIPtr(self.dut.GetDPIHandle("io_rdata_0_brMask_1", 0), self.dut.GetDPIHandle("io_rdata_0_brMask_1", 1))
        self.io_rdata_0_brMask_2.BindDPIPtr(self.dut.GetDPIHandle("io_rdata_0_brMask_2", 0), self.dut.GetDPIHandle("io_rdata_0_brMask_2", 1))
        self.io_rdata_0_brMask_3.BindDPIPtr(self.dut.GetDPIHandle("io_rdata_0_brMask_3", 0), self.dut.GetDPIHandle("io_rdata_0_brMask_3", 1))
        self.io_rdata_0_brMask_4.BindDPIPtr(self.dut.GetDPIHandle("io_rdata_0_brMask_4", 0), self.dut.GetDPIHandle("io_rdata_0_brMask_4", 1))
        self.io_rdata_0_brMask_5.BindDPIPtr(self.dut.GetDPIHandle("io_rdata_0_brMask_5", 0), self.dut.GetDPIHandle("io_rdata_0_brMask_5", 1))
        self.io_rdata_0_brMask_6.BindDPIPtr(self.dut.GetDPIHandle("io_rdata_0_brMask_6", 0), self.dut.GetDPIHandle("io_rdata_0_brMask_6", 1))
        self.io_rdata_0_brMask_7.BindDPIPtr(self.dut.GetDPIHandle("io_rdata_0_brMask_7", 0), self.dut.GetDPIHandle("io_rdata_0_brMask_7", 1))
        self.io_rdata_0_brMask_8.BindDPIPtr(self.dut.GetDPIHandle("io_rdata_0_brMask_8", 0), self.dut.GetDPIHandle("io_rdata_0_brMask_8", 1))
        self.io_rdata_0_brMask_9.BindDPIPtr(self.dut.GetDPIHandle("io_rdata_0_brMask_9", 0), self.dut.GetDPIHandle("io_rdata_0_brMask_9", 1))
        self.io_rdata_0_brMask_10.BindDPIPtr(self.dut.GetDPIHandle("io_rdata_0_brMask_10", 0), self.dut.GetDPIHandle("io_rdata_0_brMask_10", 1))
        self.io_rdata_0_brMask_11.BindDPIPtr(self.dut.GetDPIHandle("io_rdata_0_brMask_11", 0), self.dut.GetDPIHandle("io_rdata_0_brMask_11", 1))
        self.io_rdata_0_brMask_12.BindDPIPtr(self.dut.GetDPIHandle("io_rdata_0_brMask_12", 0), self.dut.GetDPIHandle("io_rdata_0_brMask_12", 1))
        self.io_rdata_0_brMask_13.BindDPIPtr(self.dut.GetDPIHandle("io_rdata_0_brMask_13", 0), self.dut.GetDPIHandle("io_rdata_0_brMask_13", 1))
        self.io_rdata_0_brMask_14.BindDPIPtr(self.dut.GetDPIHandle("io_rdata_0_brMask_14", 0), self.dut.GetDPIHandle("io_rdata_0_brMask_14", 1))
        self.io_rdata_0_brMask_15.BindDPIPtr(self.dut.GetDPIHandle("io_rdata_0_brMask_15", 0), self.dut.GetDPIHandle("io_rdata_0_brMask_15", 1))
        self.io_rdata_0_jmpInfo_valid.BindDPIPtr(self.dut.GetDPIHandle("io_rdata_0_jmpInfo_valid", 0), self.dut.GetDPIHandle("io_rdata_0_jmpInfo_valid", 1))
        self.io_rdata_0_jmpInfo_bits_0.BindDPIPtr(self.dut.GetDPIHandle("io_rdata_0_jmpInfo_bits_0", 0), self.dut.GetDPIHandle("io_rdata_0_jmpInfo_bits_0", 1))
        self.io_rdata_0_jmpInfo_bits_1.BindDPIPtr(self.dut.GetDPIHandle("io_rdata_0_jmpInfo_bits_1", 0), self.dut.GetDPIHandle("io_rdata_0_jmpInfo_bits_1", 1))
        self.io_rdata_0_jmpInfo_bits_2.BindDPIPtr(self.dut.GetDPIHandle("io_rdata_0_jmpInfo_bits_2", 0), self.dut.GetDPIHandle("io_rdata_0_jmpInfo_bits_2", 1))
        self.io_rdata_0_jmpOffset.BindDPIPtr(self.dut.GetDPIHandle("io_rdata_0_jmpOffset", 0), self.dut.GetDPIHandle("io_rdata_0_jmpOffset", 1))
        self.io_rdata_0_rvcMask_0.BindDPIPtr(self.dut.GetDPIHandle("io_rdata_0_rvcMask_0", 0), self.dut.GetDPIHandle("io_rdata_0_rvcMask_0", 1))
        self.io_rdata_0_rvcMask_1.BindDPIPtr(self.dut.GetDPIHandle("io_rdata_0_rvcMask_1", 0), self.dut.GetDPIHandle("io_rdata_0_rvcMask_1", 1))
        self.io_rdata_0_rvcMask_2.BindDPIPtr(self.dut.GetDPIHandle("io_rdata_0_rvcMask_2", 0), self.dut.GetDPIHandle("io_rdata_0_rvcMask_2", 1))
        self.io_rdata_0_rvcMask_3.BindDPIPtr(self.dut.GetDPIHandle("io_rdata_0_rvcMask_3", 0), self.dut.GetDPIHandle("io_rdata_0_rvcMask_3", 1))
        self.io_rdata_0_rvcMask_4.BindDPIPtr(self.dut.GetDPIHandle("io_rdata_0_rvcMask_4", 0), self.dut.GetDPIHandle("io_rdata_0_rvcMask_4", 1))
        self.io_rdata_0_rvcMask_5.BindDPIPtr(self.dut.GetDPIHandle("io_rdata_0_rvcMask_5", 0), self.dut.GetDPIHandle("io_rdata_0_rvcMask_5", 1))
        self.io_rdata_0_rvcMask_6.BindDPIPtr(self.dut.GetDPIHandle("io_rdata_0_rvcMask_6", 0), self.dut.GetDPIHandle("io_rdata_0_rvcMask_6", 1))
        self.io_rdata_0_rvcMask_7.BindDPIPtr(self.dut.GetDPIHandle("io_rdata_0_rvcMask_7", 0), self.dut.GetDPIHandle("io_rdata_0_rvcMask_7", 1))
        self.io_rdata_0_rvcMask_8.BindDPIPtr(self.dut.GetDPIHandle("io_rdata_0_rvcMask_8", 0), self.dut.GetDPIHandle("io_rdata_0_rvcMask_8", 1))
        self.io_rdata_0_rvcMask_9.BindDPIPtr(self.dut.GetDPIHandle("io_rdata_0_rvcMask_9", 0), self.dut.GetDPIHandle("io_rdata_0_rvcMask_9", 1))
        self.io_rdata_0_rvcMask_10.BindDPIPtr(self.dut.GetDPIHandle("io_rdata_0_rvcMask_10", 0), self.dut.GetDPIHandle("io_rdata_0_rvcMask_10", 1))
        self.io_rdata_0_rvcMask_11.BindDPIPtr(self.dut.GetDPIHandle("io_rdata_0_rvcMask_11", 0), self.dut.GetDPIHandle("io_rdata_0_rvcMask_11", 1))
        self.io_rdata_0_rvcMask_12.BindDPIPtr(self.dut.GetDPIHandle("io_rdata_0_rvcMask_12", 0), self.dut.GetDPIHandle("io_rdata_0_rvcMask_12", 1))
        self.io_rdata_0_rvcMask_13.BindDPIPtr(self.dut.GetDPIHandle("io_rdata_0_rvcMask_13", 0), self.dut.GetDPIHandle("io_rdata_0_rvcMask_13", 1))
        self.io_rdata_0_rvcMask_14.BindDPIPtr(self.dut.GetDPIHandle("io_rdata_0_rvcMask_14", 0), self.dut.GetDPIHandle("io_rdata_0_rvcMask_14", 1))
        self.io_rdata_0_rvcMask_15.BindDPIPtr(self.dut.GetDPIHandle("io_rdata_0_rvcMask_15", 0), self.dut.GetDPIHandle("io_rdata_0_rvcMask_15", 1))
        self.io_rdata_1_brMask_0.BindDPIPtr(self.dut.GetDPIHandle("io_rdata_1_brMask_0", 0), self.dut.GetDPIHandle("io_rdata_1_brMask_0", 1))
        self.io_rdata_1_brMask_1.BindDPIPtr(self.dut.GetDPIHandle("io_rdata_1_brMask_1", 0), self.dut.GetDPIHandle("io_rdata_1_brMask_1", 1))
        self.io_rdata_1_brMask_2.BindDPIPtr(self.dut.GetDPIHandle("io_rdata_1_brMask_2", 0), self.dut.GetDPIHandle("io_rdata_1_brMask_2", 1))
        self.io_rdata_1_brMask_3.BindDPIPtr(self.dut.GetDPIHandle("io_rdata_1_brMask_3", 0), self.dut.GetDPIHandle("io_rdata_1_brMask_3", 1))
        self.io_rdata_1_brMask_4.BindDPIPtr(self.dut.GetDPIHandle("io_rdata_1_brMask_4", 0), self.dut.GetDPIHandle("io_rdata_1_brMask_4", 1))
        self.io_rdata_1_brMask_5.BindDPIPtr(self.dut.GetDPIHandle("io_rdata_1_brMask_5", 0), self.dut.GetDPIHandle("io_rdata_1_brMask_5", 1))
        self.io_rdata_1_brMask_6.BindDPIPtr(self.dut.GetDPIHandle("io_rdata_1_brMask_6", 0), self.dut.GetDPIHandle("io_rdata_1_brMask_6", 1))
        self.io_rdata_1_brMask_7.BindDPIPtr(self.dut.GetDPIHandle("io_rdata_1_brMask_7", 0), self.dut.GetDPIHandle("io_rdata_1_brMask_7", 1))
        self.io_rdata_1_brMask_8.BindDPIPtr(self.dut.GetDPIHandle("io_rdata_1_brMask_8", 0), self.dut.GetDPIHandle("io_rdata_1_brMask_8", 1))
        self.io_rdata_1_brMask_9.BindDPIPtr(self.dut.GetDPIHandle("io_rdata_1_brMask_9", 0), self.dut.GetDPIHandle("io_rdata_1_brMask_9", 1))
        self.io_rdata_1_brMask_10.BindDPIPtr(self.dut.GetDPIHandle("io_rdata_1_brMask_10", 0), self.dut.GetDPIHandle("io_rdata_1_brMask_10", 1))
        self.io_rdata_1_brMask_11.BindDPIPtr(self.dut.GetDPIHandle("io_rdata_1_brMask_11", 0), self.dut.GetDPIHandle("io_rdata_1_brMask_11", 1))
        self.io_rdata_1_brMask_12.BindDPIPtr(self.dut.GetDPIHandle("io_rdata_1_brMask_12", 0), self.dut.GetDPIHandle("io_rdata_1_brMask_12", 1))
        self.io_rdata_1_brMask_13.BindDPIPtr(self.dut.GetDPIHandle("io_rdata_1_brMask_13", 0), self.dut.GetDPIHandle("io_rdata_1_brMask_13", 1))
        self.io_rdata_1_brMask_14.BindDPIPtr(self.dut.GetDPIHandle("io_rdata_1_brMask_14", 0), self.dut.GetDPIHandle("io_rdata_1_brMask_14", 1))
        self.io_rdata_1_brMask_15.BindDPIPtr(self.dut.GetDPIHandle("io_rdata_1_brMask_15", 0), self.dut.GetDPIHandle("io_rdata_1_brMask_15", 1))
        self.io_rdata_1_jmpInfo_valid.BindDPIPtr(self.dut.GetDPIHandle("io_rdata_1_jmpInfo_valid", 0), self.dut.GetDPIHandle("io_rdata_1_jmpInfo_valid", 1))
        self.io_rdata_1_jmpInfo_bits_0.BindDPIPtr(self.dut.GetDPIHandle("io_rdata_1_jmpInfo_bits_0", 0), self.dut.GetDPIHandle("io_rdata_1_jmpInfo_bits_0", 1))
        self.io_rdata_1_jmpInfo_bits_1.BindDPIPtr(self.dut.GetDPIHandle("io_rdata_1_jmpInfo_bits_1", 0), self.dut.GetDPIHandle("io_rdata_1_jmpInfo_bits_1", 1))
        self.io_rdata_1_jmpInfo_bits_2.BindDPIPtr(self.dut.GetDPIHandle("io_rdata_1_jmpInfo_bits_2", 0), self.dut.GetDPIHandle("io_rdata_1_jmpInfo_bits_2", 1))
        self.io_rdata_1_jmpOffset.BindDPIPtr(self.dut.GetDPIHandle("io_rdata_1_jmpOffset", 0), self.dut.GetDPIHandle("io_rdata_1_jmpOffset", 1))
        self.io_rdata_1_jalTarget.BindDPIPtr(self.dut.GetDPIHandle("io_rdata_1_jalTarget", 0), self.dut.GetDPIHandle("io_rdata_1_jalTarget", 1))
        self.io_rdata_1_rvcMask_0.BindDPIPtr(self.dut.GetDPIHandle("io_rdata_1_rvcMask_0", 0), self.dut.GetDPIHandle("io_rdata_1_rvcMask_0", 1))
        self.io_rdata_1_rvcMask_1.BindDPIPtr(self.dut.GetDPIHandle("io_rdata_1_rvcMask_1", 0), self.dut.GetDPIHandle("io_rdata_1_rvcMask_1", 1))
        self.io_rdata_1_rvcMask_2.BindDPIPtr(self.dut.GetDPIHandle("io_rdata_1_rvcMask_2", 0), self.dut.GetDPIHandle("io_rdata_1_rvcMask_2", 1))
        self.io_rdata_1_rvcMask_3.BindDPIPtr(self.dut.GetDPIHandle("io_rdata_1_rvcMask_3", 0), self.dut.GetDPIHandle("io_rdata_1_rvcMask_3", 1))
        self.io_rdata_1_rvcMask_4.BindDPIPtr(self.dut.GetDPIHandle("io_rdata_1_rvcMask_4", 0), self.dut.GetDPIHandle("io_rdata_1_rvcMask_4", 1))
        self.io_rdata_1_rvcMask_5.BindDPIPtr(self.dut.GetDPIHandle("io_rdata_1_rvcMask_5", 0), self.dut.GetDPIHandle("io_rdata_1_rvcMask_5", 1))
        self.io_rdata_1_rvcMask_6.BindDPIPtr(self.dut.GetDPIHandle("io_rdata_1_rvcMask_6", 0), self.dut.GetDPIHandle("io_rdata_1_rvcMask_6", 1))
        self.io_rdata_1_rvcMask_7.BindDPIPtr(self.dut.GetDPIHandle("io_rdata_1_rvcMask_7", 0), self.dut.GetDPIHandle("io_rdata_1_rvcMask_7", 1))
        self.io_rdata_1_rvcMask_8.BindDPIPtr(self.dut.GetDPIHandle("io_rdata_1_rvcMask_8", 0), self.dut.GetDPIHandle("io_rdata_1_rvcMask_8", 1))
        self.io_rdata_1_rvcMask_9.BindDPIPtr(self.dut.GetDPIHandle("io_rdata_1_rvcMask_9", 0), self.dut.GetDPIHandle("io_rdata_1_rvcMask_9", 1))
        self.io_rdata_1_rvcMask_10.BindDPIPtr(self.dut.GetDPIHandle("io_rdata_1_rvcMask_10", 0), self.dut.GetDPIHandle("io_rdata_1_rvcMask_10", 1))
        self.io_rdata_1_rvcMask_11.BindDPIPtr(self.dut.GetDPIHandle("io_rdata_1_rvcMask_11", 0), self.dut.GetDPIHandle("io_rdata_1_rvcMask_11", 1))
        self.io_rdata_1_rvcMask_12.BindDPIPtr(self.dut.GetDPIHandle("io_rdata_1_rvcMask_12", 0), self.dut.GetDPIHandle("io_rdata_1_rvcMask_12", 1))
        self.io_rdata_1_rvcMask_13.BindDPIPtr(self.dut.GetDPIHandle("io_rdata_1_rvcMask_13", 0), self.dut.GetDPIHandle("io_rdata_1_rvcMask_13", 1))
        self.io_rdata_1_rvcMask_14.BindDPIPtr(self.dut.GetDPIHandle("io_rdata_1_rvcMask_14", 0), self.dut.GetDPIHandle("io_rdata_1_rvcMask_14", 1))
        self.io_rdata_1_rvcMask_15.BindDPIPtr(self.dut.GetDPIHandle("io_rdata_1_rvcMask_15", 0), self.dut.GetDPIHandle("io_rdata_1_rvcMask_15", 1))
        self.io_wen_0.BindDPIPtr(self.dut.GetDPIHandle("io_wen_0", 0), self.dut.GetDPIHandle("io_wen_0", 1))
        self.io_waddr_0.BindDPIPtr(self.dut.GetDPIHandle("io_waddr_0", 0), self.dut.GetDPIHandle("io_waddr_0", 1))
        self.io_wdata_0_brMask_0.BindDPIPtr(self.dut.GetDPIHandle("io_wdata_0_brMask_0", 0), self.dut.GetDPIHandle("io_wdata_0_brMask_0", 1))
        self.io_wdata_0_brMask_1.BindDPIPtr(self.dut.GetDPIHandle("io_wdata_0_brMask_1", 0), self.dut.GetDPIHandle("io_wdata_0_brMask_1", 1))
        self.io_wdata_0_brMask_2.BindDPIPtr(self.dut.GetDPIHandle("io_wdata_0_brMask_2", 0), self.dut.GetDPIHandle("io_wdata_0_brMask_2", 1))
        self.io_wdata_0_brMask_3.BindDPIPtr(self.dut.GetDPIHandle("io_wdata_0_brMask_3", 0), self.dut.GetDPIHandle("io_wdata_0_brMask_3", 1))
        self.io_wdata_0_brMask_4.BindDPIPtr(self.dut.GetDPIHandle("io_wdata_0_brMask_4", 0), self.dut.GetDPIHandle("io_wdata_0_brMask_4", 1))
        self.io_wdata_0_brMask_5.BindDPIPtr(self.dut.GetDPIHandle("io_wdata_0_brMask_5", 0), self.dut.GetDPIHandle("io_wdata_0_brMask_5", 1))
        self.io_wdata_0_brMask_6.BindDPIPtr(self.dut.GetDPIHandle("io_wdata_0_brMask_6", 0), self.dut.GetDPIHandle("io_wdata_0_brMask_6", 1))
        self.io_wdata_0_brMask_7.BindDPIPtr(self.dut.GetDPIHandle("io_wdata_0_brMask_7", 0), self.dut.GetDPIHandle("io_wdata_0_brMask_7", 1))
        self.io_wdata_0_brMask_8.BindDPIPtr(self.dut.GetDPIHandle("io_wdata_0_brMask_8", 0), self.dut.GetDPIHandle("io_wdata_0_brMask_8", 1))
        self.io_wdata_0_brMask_9.BindDPIPtr(self.dut.GetDPIHandle("io_wdata_0_brMask_9", 0), self.dut.GetDPIHandle("io_wdata_0_brMask_9", 1))
        self.io_wdata_0_brMask_10.BindDPIPtr(self.dut.GetDPIHandle("io_wdata_0_brMask_10", 0), self.dut.GetDPIHandle("io_wdata_0_brMask_10", 1))
        self.io_wdata_0_brMask_11.BindDPIPtr(self.dut.GetDPIHandle("io_wdata_0_brMask_11", 0), self.dut.GetDPIHandle("io_wdata_0_brMask_11", 1))
        self.io_wdata_0_brMask_12.BindDPIPtr(self.dut.GetDPIHandle("io_wdata_0_brMask_12", 0), self.dut.GetDPIHandle("io_wdata_0_brMask_12", 1))
        self.io_wdata_0_brMask_13.BindDPIPtr(self.dut.GetDPIHandle("io_wdata_0_brMask_13", 0), self.dut.GetDPIHandle("io_wdata_0_brMask_13", 1))
        self.io_wdata_0_brMask_14.BindDPIPtr(self.dut.GetDPIHandle("io_wdata_0_brMask_14", 0), self.dut.GetDPIHandle("io_wdata_0_brMask_14", 1))
        self.io_wdata_0_brMask_15.BindDPIPtr(self.dut.GetDPIHandle("io_wdata_0_brMask_15", 0), self.dut.GetDPIHandle("io_wdata_0_brMask_15", 1))
        self.io_wdata_0_jmpInfo_valid.BindDPIPtr(self.dut.GetDPIHandle("io_wdata_0_jmpInfo_valid", 0), self.dut.GetDPIHandle("io_wdata_0_jmpInfo_valid", 1))
        self.io_wdata_0_jmpInfo_bits_0.BindDPIPtr(self.dut.GetDPIHandle("io_wdata_0_jmpInfo_bits_0", 0), self.dut.GetDPIHandle("io_wdata_0_jmpInfo_bits_0", 1))
        self.io_wdata_0_jmpInfo_bits_1.BindDPIPtr(self.dut.GetDPIHandle("io_wdata_0_jmpInfo_bits_1", 0), self.dut.GetDPIHandle("io_wdata_0_jmpInfo_bits_1", 1))
        self.io_wdata_0_jmpInfo_bits_2.BindDPIPtr(self.dut.GetDPIHandle("io_wdata_0_jmpInfo_bits_2", 0), self.dut.GetDPIHandle("io_wdata_0_jmpInfo_bits_2", 1))
        self.io_wdata_0_jmpOffset.BindDPIPtr(self.dut.GetDPIHandle("io_wdata_0_jmpOffset", 0), self.dut.GetDPIHandle("io_wdata_0_jmpOffset", 1))
        self.io_wdata_0_jalTarget.BindDPIPtr(self.dut.GetDPIHandle("io_wdata_0_jalTarget", 0), self.dut.GetDPIHandle("io_wdata_0_jalTarget", 1))
        self.io_wdata_0_rvcMask_0.BindDPIPtr(self.dut.GetDPIHandle("io_wdata_0_rvcMask_0", 0), self.dut.GetDPIHandle("io_wdata_0_rvcMask_0", 1))
        self.io_wdata_0_rvcMask_1.BindDPIPtr(self.dut.GetDPIHandle("io_wdata_0_rvcMask_1", 0), self.dut.GetDPIHandle("io_wdata_0_rvcMask_1", 1))
        self.io_wdata_0_rvcMask_2.BindDPIPtr(self.dut.GetDPIHandle("io_wdata_0_rvcMask_2", 0), self.dut.GetDPIHandle("io_wdata_0_rvcMask_2", 1))
        self.io_wdata_0_rvcMask_3.BindDPIPtr(self.dut.GetDPIHandle("io_wdata_0_rvcMask_3", 0), self.dut.GetDPIHandle("io_wdata_0_rvcMask_3", 1))
        self.io_wdata_0_rvcMask_4.BindDPIPtr(self.dut.GetDPIHandle("io_wdata_0_rvcMask_4", 0), self.dut.GetDPIHandle("io_wdata_0_rvcMask_4", 1))
        self.io_wdata_0_rvcMask_5.BindDPIPtr(self.dut.GetDPIHandle("io_wdata_0_rvcMask_5", 0), self.dut.GetDPIHandle("io_wdata_0_rvcMask_5", 1))
        self.io_wdata_0_rvcMask_6.BindDPIPtr(self.dut.GetDPIHandle("io_wdata_0_rvcMask_6", 0), self.dut.GetDPIHandle("io_wdata_0_rvcMask_6", 1))
        self.io_wdata_0_rvcMask_7.BindDPIPtr(self.dut.GetDPIHandle("io_wdata_0_rvcMask_7", 0), self.dut.GetDPIHandle("io_wdata_0_rvcMask_7", 1))
        self.io_wdata_0_rvcMask_8.BindDPIPtr(self.dut.GetDPIHandle("io_wdata_0_rvcMask_8", 0), self.dut.GetDPIHandle("io_wdata_0_rvcMask_8", 1))
        self.io_wdata_0_rvcMask_9.BindDPIPtr(self.dut.GetDPIHandle("io_wdata_0_rvcMask_9", 0), self.dut.GetDPIHandle("io_wdata_0_rvcMask_9", 1))
        self.io_wdata_0_rvcMask_10.BindDPIPtr(self.dut.GetDPIHandle("io_wdata_0_rvcMask_10", 0), self.dut.GetDPIHandle("io_wdata_0_rvcMask_10", 1))
        self.io_wdata_0_rvcMask_11.BindDPIPtr(self.dut.GetDPIHandle("io_wdata_0_rvcMask_11", 0), self.dut.GetDPIHandle("io_wdata_0_rvcMask_11", 1))
        self.io_wdata_0_rvcMask_12.BindDPIPtr(self.dut.GetDPIHandle("io_wdata_0_rvcMask_12", 0), self.dut.GetDPIHandle("io_wdata_0_rvcMask_12", 1))
        self.io_wdata_0_rvcMask_13.BindDPIPtr(self.dut.GetDPIHandle("io_wdata_0_rvcMask_13", 0), self.dut.GetDPIHandle("io_wdata_0_rvcMask_13", 1))
        self.io_wdata_0_rvcMask_14.BindDPIPtr(self.dut.GetDPIHandle("io_wdata_0_rvcMask_14", 0), self.dut.GetDPIHandle("io_wdata_0_rvcMask_14", 1))
        self.io_wdata_0_rvcMask_15.BindDPIPtr(self.dut.GetDPIHandle("io_wdata_0_rvcMask_15", 0), self.dut.GetDPIHandle("io_wdata_0_rvcMask_15", 1))


        # Add2Port
        self.xport.Add("clock", self.clock.xdata)
        self.xport.Add("reset", self.reset.xdata)
        self.xport.Add("io_ren_0", self.io_ren_0.xdata)
        self.xport.Add("io_ren_1", self.io_ren_1.xdata)
        self.xport.Add("io_raddr_0", self.io_raddr_0.xdata)
        self.xport.Add("io_raddr_1", self.io_raddr_1.xdata)
        self.xport.Add("io_rdata_0_brMask_0", self.io_rdata_0_brMask_0.xdata)
        self.xport.Add("io_rdata_0_brMask_1", self.io_rdata_0_brMask_1.xdata)
        self.xport.Add("io_rdata_0_brMask_2", self.io_rdata_0_brMask_2.xdata)
        self.xport.Add("io_rdata_0_brMask_3", self.io_rdata_0_brMask_3.xdata)
        self.xport.Add("io_rdata_0_brMask_4", self.io_rdata_0_brMask_4.xdata)
        self.xport.Add("io_rdata_0_brMask_5", self.io_rdata_0_brMask_5.xdata)
        self.xport.Add("io_rdata_0_brMask_6", self.io_rdata_0_brMask_6.xdata)
        self.xport.Add("io_rdata_0_brMask_7", self.io_rdata_0_brMask_7.xdata)
        self.xport.Add("io_rdata_0_brMask_8", self.io_rdata_0_brMask_8.xdata)
        self.xport.Add("io_rdata_0_brMask_9", self.io_rdata_0_brMask_9.xdata)
        self.xport.Add("io_rdata_0_brMask_10", self.io_rdata_0_brMask_10.xdata)
        self.xport.Add("io_rdata_0_brMask_11", self.io_rdata_0_brMask_11.xdata)
        self.xport.Add("io_rdata_0_brMask_12", self.io_rdata_0_brMask_12.xdata)
        self.xport.Add("io_rdata_0_brMask_13", self.io_rdata_0_brMask_13.xdata)
        self.xport.Add("io_rdata_0_brMask_14", self.io_rdata_0_brMask_14.xdata)
        self.xport.Add("io_rdata_0_brMask_15", self.io_rdata_0_brMask_15.xdata)
        self.xport.Add("io_rdata_0_jmpInfo_valid", self.io_rdata_0_jmpInfo_valid.xdata)
        self.xport.Add("io_rdata_0_jmpInfo_bits_0", self.io_rdata_0_jmpInfo_bits_0.xdata)
        self.xport.Add("io_rdata_0_jmpInfo_bits_1", self.io_rdata_0_jmpInfo_bits_1.xdata)
        self.xport.Add("io_rdata_0_jmpInfo_bits_2", self.io_rdata_0_jmpInfo_bits_2.xdata)
        self.xport.Add("io_rdata_0_jmpOffset", self.io_rdata_0_jmpOffset.xdata)
        self.xport.Add("io_rdata_0_rvcMask_0", self.io_rdata_0_rvcMask_0.xdata)
        self.xport.Add("io_rdata_0_rvcMask_1", self.io_rdata_0_rvcMask_1.xdata)
        self.xport.Add("io_rdata_0_rvcMask_2", self.io_rdata_0_rvcMask_2.xdata)
        self.xport.Add("io_rdata_0_rvcMask_3", self.io_rdata_0_rvcMask_3.xdata)
        self.xport.Add("io_rdata_0_rvcMask_4", self.io_rdata_0_rvcMask_4.xdata)
        self.xport.Add("io_rdata_0_rvcMask_5", self.io_rdata_0_rvcMask_5.xdata)
        self.xport.Add("io_rdata_0_rvcMask_6", self.io_rdata_0_rvcMask_6.xdata)
        self.xport.Add("io_rdata_0_rvcMask_7", self.io_rdata_0_rvcMask_7.xdata)
        self.xport.Add("io_rdata_0_rvcMask_8", self.io_rdata_0_rvcMask_8.xdata)
        self.xport.Add("io_rdata_0_rvcMask_9", self.io_rdata_0_rvcMask_9.xdata)
        self.xport.Add("io_rdata_0_rvcMask_10", self.io_rdata_0_rvcMask_10.xdata)
        self.xport.Add("io_rdata_0_rvcMask_11", self.io_rdata_0_rvcMask_11.xdata)
        self.xport.Add("io_rdata_0_rvcMask_12", self.io_rdata_0_rvcMask_12.xdata)
        self.xport.Add("io_rdata_0_rvcMask_13", self.io_rdata_0_rvcMask_13.xdata)
        self.xport.Add("io_rdata_0_rvcMask_14", self.io_rdata_0_rvcMask_14.xdata)
        self.xport.Add("io_rdata_0_rvcMask_15", self.io_rdata_0_rvcMask_15.xdata)
        self.xport.Add("io_rdata_1_brMask_0", self.io_rdata_1_brMask_0.xdata)
        self.xport.Add("io_rdata_1_brMask_1", self.io_rdata_1_brMask_1.xdata)
        self.xport.Add("io_rdata_1_brMask_2", self.io_rdata_1_brMask_2.xdata)
        self.xport.Add("io_rdata_1_brMask_3", self.io_rdata_1_brMask_3.xdata)
        self.xport.Add("io_rdata_1_brMask_4", self.io_rdata_1_brMask_4.xdata)
        self.xport.Add("io_rdata_1_brMask_5", self.io_rdata_1_brMask_5.xdata)
        self.xport.Add("io_rdata_1_brMask_6", self.io_rdata_1_brMask_6.xdata)
        self.xport.Add("io_rdata_1_brMask_7", self.io_rdata_1_brMask_7.xdata)
        self.xport.Add("io_rdata_1_brMask_8", self.io_rdata_1_brMask_8.xdata)
        self.xport.Add("io_rdata_1_brMask_9", self.io_rdata_1_brMask_9.xdata)
        self.xport.Add("io_rdata_1_brMask_10", self.io_rdata_1_brMask_10.xdata)
        self.xport.Add("io_rdata_1_brMask_11", self.io_rdata_1_brMask_11.xdata)
        self.xport.Add("io_rdata_1_brMask_12", self.io_rdata_1_brMask_12.xdata)
        self.xport.Add("io_rdata_1_brMask_13", self.io_rdata_1_brMask_13.xdata)
        self.xport.Add("io_rdata_1_brMask_14", self.io_rdata_1_brMask_14.xdata)
        self.xport.Add("io_rdata_1_brMask_15", self.io_rdata_1_brMask_15.xdata)
        self.xport.Add("io_rdata_1_jmpInfo_valid", self.io_rdata_1_jmpInfo_valid.xdata)
        self.xport.Add("io_rdata_1_jmpInfo_bits_0", self.io_rdata_1_jmpInfo_bits_0.xdata)
        self.xport.Add("io_rdata_1_jmpInfo_bits_1", self.io_rdata_1_jmpInfo_bits_1.xdata)
        self.xport.Add("io_rdata_1_jmpInfo_bits_2", self.io_rdata_1_jmpInfo_bits_2.xdata)
        self.xport.Add("io_rdata_1_jmpOffset", self.io_rdata_1_jmpOffset.xdata)
        self.xport.Add("io_rdata_1_jalTarget", self.io_rdata_1_jalTarget.xdata)
        self.xport.Add("io_rdata_1_rvcMask_0", self.io_rdata_1_rvcMask_0.xdata)
        self.xport.Add("io_rdata_1_rvcMask_1", self.io_rdata_1_rvcMask_1.xdata)
        self.xport.Add("io_rdata_1_rvcMask_2", self.io_rdata_1_rvcMask_2.xdata)
        self.xport.Add("io_rdata_1_rvcMask_3", self.io_rdata_1_rvcMask_3.xdata)
        self.xport.Add("io_rdata_1_rvcMask_4", self.io_rdata_1_rvcMask_4.xdata)
        self.xport.Add("io_rdata_1_rvcMask_5", self.io_rdata_1_rvcMask_5.xdata)
        self.xport.Add("io_rdata_1_rvcMask_6", self.io_rdata_1_rvcMask_6.xdata)
        self.xport.Add("io_rdata_1_rvcMask_7", self.io_rdata_1_rvcMask_7.xdata)
        self.xport.Add("io_rdata_1_rvcMask_8", self.io_rdata_1_rvcMask_8.xdata)
        self.xport.Add("io_rdata_1_rvcMask_9", self.io_rdata_1_rvcMask_9.xdata)
        self.xport.Add("io_rdata_1_rvcMask_10", self.io_rdata_1_rvcMask_10.xdata)
        self.xport.Add("io_rdata_1_rvcMask_11", self.io_rdata_1_rvcMask_11.xdata)
        self.xport.Add("io_rdata_1_rvcMask_12", self.io_rdata_1_rvcMask_12.xdata)
        self.xport.Add("io_rdata_1_rvcMask_13", self.io_rdata_1_rvcMask_13.xdata)
        self.xport.Add("io_rdata_1_rvcMask_14", self.io_rdata_1_rvcMask_14.xdata)
        self.xport.Add("io_rdata_1_rvcMask_15", self.io_rdata_1_rvcMask_15.xdata)
        self.xport.Add("io_wen_0", self.io_wen_0.xdata)
        self.xport.Add("io_waddr_0", self.io_waddr_0.xdata)
        self.xport.Add("io_wdata_0_brMask_0", self.io_wdata_0_brMask_0.xdata)
        self.xport.Add("io_wdata_0_brMask_1", self.io_wdata_0_brMask_1.xdata)
        self.xport.Add("io_wdata_0_brMask_2", self.io_wdata_0_brMask_2.xdata)
        self.xport.Add("io_wdata_0_brMask_3", self.io_wdata_0_brMask_3.xdata)
        self.xport.Add("io_wdata_0_brMask_4", self.io_wdata_0_brMask_4.xdata)
        self.xport.Add("io_wdata_0_brMask_5", self.io_wdata_0_brMask_5.xdata)
        self.xport.Add("io_wdata_0_brMask_6", self.io_wdata_0_brMask_6.xdata)
        self.xport.Add("io_wdata_0_brMask_7", self.io_wdata_0_brMask_7.xdata)
        self.xport.Add("io_wdata_0_brMask_8", self.io_wdata_0_brMask_8.xdata)
        self.xport.Add("io_wdata_0_brMask_9", self.io_wdata_0_brMask_9.xdata)
        self.xport.Add("io_wdata_0_brMask_10", self.io_wdata_0_brMask_10.xdata)
        self.xport.Add("io_wdata_0_brMask_11", self.io_wdata_0_brMask_11.xdata)
        self.xport.Add("io_wdata_0_brMask_12", self.io_wdata_0_brMask_12.xdata)
        self.xport.Add("io_wdata_0_brMask_13", self.io_wdata_0_brMask_13.xdata)
        self.xport.Add("io_wdata_0_brMask_14", self.io_wdata_0_brMask_14.xdata)
        self.xport.Add("io_wdata_0_brMask_15", self.io_wdata_0_brMask_15.xdata)
        self.xport.Add("io_wdata_0_jmpInfo_valid", self.io_wdata_0_jmpInfo_valid.xdata)
        self.xport.Add("io_wdata_0_jmpInfo_bits_0", self.io_wdata_0_jmpInfo_bits_0.xdata)
        self.xport.Add("io_wdata_0_jmpInfo_bits_1", self.io_wdata_0_jmpInfo_bits_1.xdata)
        self.xport.Add("io_wdata_0_jmpInfo_bits_2", self.io_wdata_0_jmpInfo_bits_2.xdata)
        self.xport.Add("io_wdata_0_jmpOffset", self.io_wdata_0_jmpOffset.xdata)
        self.xport.Add("io_wdata_0_jalTarget", self.io_wdata_0_jalTarget.xdata)
        self.xport.Add("io_wdata_0_rvcMask_0", self.io_wdata_0_rvcMask_0.xdata)
        self.xport.Add("io_wdata_0_rvcMask_1", self.io_wdata_0_rvcMask_1.xdata)
        self.xport.Add("io_wdata_0_rvcMask_2", self.io_wdata_0_rvcMask_2.xdata)
        self.xport.Add("io_wdata_0_rvcMask_3", self.io_wdata_0_rvcMask_3.xdata)
        self.xport.Add("io_wdata_0_rvcMask_4", self.io_wdata_0_rvcMask_4.xdata)
        self.xport.Add("io_wdata_0_rvcMask_5", self.io_wdata_0_rvcMask_5.xdata)
        self.xport.Add("io_wdata_0_rvcMask_6", self.io_wdata_0_rvcMask_6.xdata)
        self.xport.Add("io_wdata_0_rvcMask_7", self.io_wdata_0_rvcMask_7.xdata)
        self.xport.Add("io_wdata_0_rvcMask_8", self.io_wdata_0_rvcMask_8.xdata)
        self.xport.Add("io_wdata_0_rvcMask_9", self.io_wdata_0_rvcMask_9.xdata)
        self.xport.Add("io_wdata_0_rvcMask_10", self.io_wdata_0_rvcMask_10.xdata)
        self.xport.Add("io_wdata_0_rvcMask_11", self.io_wdata_0_rvcMask_11.xdata)
        self.xport.Add("io_wdata_0_rvcMask_12", self.io_wdata_0_rvcMask_12.xdata)
        self.xport.Add("io_wdata_0_rvcMask_13", self.io_wdata_0_rvcMask_13.xdata)
        self.xport.Add("io_wdata_0_rvcMask_14", self.io_wdata_0_rvcMask_14.xdata)
        self.xport.Add("io_wdata_0_rvcMask_15", self.io_wdata_0_rvcMask_15.xdata)


        # Cascaded ports
        self.io = self.xport.NewSubPort("io_")
        self.io_raddr = self.xport.NewSubPort("io_raddr_")
        self.io_rdata = self.xport.NewSubPort("io_rdata_")
        self.io_rdata_0 = self.xport.NewSubPort("io_rdata_0_")
        self.io_rdata_0_brMask = self.xport.NewSubPort("io_rdata_0_brMask_")
        self.io_rdata_0_jmpInfo = self.xport.NewSubPort("io_rdata_0_jmpInfo_")
        self.io_rdata_0_jmpInfo_bits = self.xport.NewSubPort("io_rdata_0_jmpInfo_bits_")
        self.io_rdata_0_rvcMask = self.xport.NewSubPort("io_rdata_0_rvcMask_")
        self.io_rdata_1 = self.xport.NewSubPort("io_rdata_1_")
        self.io_rdata_1_brMask = self.xport.NewSubPort("io_rdata_1_brMask_")
        self.io_rdata_1_jmpInfo = self.xport.NewSubPort("io_rdata_1_jmpInfo_")
        self.io_rdata_1_jmpInfo_bits = self.xport.NewSubPort("io_rdata_1_jmpInfo_bits_")
        self.io_rdata_1_rvcMask = self.xport.NewSubPort("io_rdata_1_rvcMask_")
        self.io_ren = self.xport.NewSubPort("io_ren_")
        self.io_waddr = self.xport.NewSubPort("io_waddr_")
        self.io_wdata = self.xport.NewSubPort("io_wdata_")
        self.io_wdata_0 = self.xport.NewSubPort("io_wdata_0_")
        self.io_wdata_0_brMask = self.xport.NewSubPort("io_wdata_0_brMask_")
        self.io_wdata_0_jmpInfo = self.xport.NewSubPort("io_wdata_0_jmpInfo_")
        self.io_wdata_0_jmpInfo_bits = self.xport.NewSubPort("io_wdata_0_jmpInfo_bits_")
        self.io_wdata_0_rvcMask = self.xport.NewSubPort("io_wdata_0_rvcMask_")
        self.io_wen = self.xport.NewSubPort("io_wen_")


    def __del__(self):
        self.Finish()

    ################################
    #         User APIs            #
    ################################
    def InitClock(self, name: str):
        self.xclock.Add(self.xport[name])

    def Step(self, i:int = 1):
        self.xclock.Step(i)

    def StepRis(self, callback, args=(), kwargs={}):
        self.xclock.StepRis(callback, args, kwargs)

    def StepFal(self, callback, args=(), kwargs={}):
        self.xclock.StepFal(callback, args, kwargs)

    def SetWaveform(self, filename: str):
        self.dut.SetWaveform(filename)
    
    def FlushWaveform(self):
        self.dut.FlushWaveform()

    def SetCoverage(self, filename: str):
        self.dut.SetCoverage(filename)
    
    def CheckPoint(self, name: str) -> int:
        self.dut.CheckPoint(name)

    def Restore(self, name: str) -> int:
        self.dut.Restore(name)

    def GetInternalSignal(self, name: str):
        if name not in self.internal_signals:
            signal = xsp.XData.FromVPI(self.dut.GetVPIHandleObj(name),
                                       self.dut.GetVPIFuncPtr("vpi_get"),
                                       self.dut.GetVPIFuncPtr("vpi_get_value"),
                                       self.dut.GetVPIFuncPtr("vpi_put_value"), name)
            if signal is None:
                return None
            self.internal_signals[name] = xsp.XPin(signal, self.event)
        return self.internal_signals[name]

    def VPIInternalSignalList(self, prefix="", deep=99):
        return self.dut.VPIInternalSignalList(prefix, deep)

    def Finish(self):
        self.dut.Finish()

    def RefreshComb(self):
        self.dut.RefreshComb()

    ################################
    #      End of User APIs        #
    ################################

    def __getitem__(self, key):
        return xsp.XPin(self.port[key], self.event)

    # Async APIs wrapped from XClock
    async def AStep(self,i: int):
        return await self.xclock.AStep(i)

    async def Acondition(self,fc_cheker):
        return await self.xclock.ACondition(fc_cheker)

    def RunStep(self,i: int):
        return self.xclock.RunStep(i)

    def __setattr__(self, name, value):
        assert not isinstance(getattr(self, name, None),
                              (xsp.XPin, xsp.XData)), \
        f"XPin and XData of DUT are read-only, do you mean to set the value of the signal? please use `{name}.value = ` instead."
        return super().__setattr__(name, value)


if __name__=="__main__":
    dut=DUTFtqPdMem()
    dut.Step(100)
