// Generated by CIRCT firtool-1.62.1
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module SyncDataModuleTemplate__64entry_2(
  input         clock,
  input         reset,
  input         io_ren_0,
  input         io_ren_1,
  input  [5:0]  io_raddr_0,
  input  [5:0]  io_raddr_1,
  output        io_rdata_0_brMask_0,
  output        io_rdata_0_brMask_1,
  output        io_rdata_0_brMask_2,
  output        io_rdata_0_brMask_3,
  output        io_rdata_0_brMask_4,
  output        io_rdata_0_brMask_5,
  output        io_rdata_0_brMask_6,
  output        io_rdata_0_brMask_7,
  output        io_rdata_0_brMask_8,
  output        io_rdata_0_brMask_9,
  output        io_rdata_0_brMask_10,
  output        io_rdata_0_brMask_11,
  output        io_rdata_0_brMask_12,
  output        io_rdata_0_brMask_13,
  output        io_rdata_0_brMask_14,
  output        io_rdata_0_brMask_15,
  output        io_rdata_0_jmpInfo_valid,
  output        io_rdata_0_jmpInfo_bits_0,
  output        io_rdata_0_jmpInfo_bits_1,
  output        io_rdata_0_jmpInfo_bits_2,
  output [3:0]  io_rdata_0_jmpOffset,
  output        io_rdata_0_rvcMask_0,
  output        io_rdata_0_rvcMask_1,
  output        io_rdata_0_rvcMask_2,
  output        io_rdata_0_rvcMask_3,
  output        io_rdata_0_rvcMask_4,
  output        io_rdata_0_rvcMask_5,
  output        io_rdata_0_rvcMask_6,
  output        io_rdata_0_rvcMask_7,
  output        io_rdata_0_rvcMask_8,
  output        io_rdata_0_rvcMask_9,
  output        io_rdata_0_rvcMask_10,
  output        io_rdata_0_rvcMask_11,
  output        io_rdata_0_rvcMask_12,
  output        io_rdata_0_rvcMask_13,
  output        io_rdata_0_rvcMask_14,
  output        io_rdata_0_rvcMask_15,
  output        io_rdata_1_brMask_0,
  output        io_rdata_1_brMask_1,
  output        io_rdata_1_brMask_2,
  output        io_rdata_1_brMask_3,
  output        io_rdata_1_brMask_4,
  output        io_rdata_1_brMask_5,
  output        io_rdata_1_brMask_6,
  output        io_rdata_1_brMask_7,
  output        io_rdata_1_brMask_8,
  output        io_rdata_1_brMask_9,
  output        io_rdata_1_brMask_10,
  output        io_rdata_1_brMask_11,
  output        io_rdata_1_brMask_12,
  output        io_rdata_1_brMask_13,
  output        io_rdata_1_brMask_14,
  output        io_rdata_1_brMask_15,
  output        io_rdata_1_jmpInfo_valid,
  output        io_rdata_1_jmpInfo_bits_0,
  output        io_rdata_1_jmpInfo_bits_1,
  output        io_rdata_1_jmpInfo_bits_2,
  output [3:0]  io_rdata_1_jmpOffset,
  output [49:0] io_rdata_1_jalTarget,
  output        io_rdata_1_rvcMask_0,
  output        io_rdata_1_rvcMask_1,
  output        io_rdata_1_rvcMask_2,
  output        io_rdata_1_rvcMask_3,
  output        io_rdata_1_rvcMask_4,
  output        io_rdata_1_rvcMask_5,
  output        io_rdata_1_rvcMask_6,
  output        io_rdata_1_rvcMask_7,
  output        io_rdata_1_rvcMask_8,
  output        io_rdata_1_rvcMask_9,
  output        io_rdata_1_rvcMask_10,
  output        io_rdata_1_rvcMask_11,
  output        io_rdata_1_rvcMask_12,
  output        io_rdata_1_rvcMask_13,
  output        io_rdata_1_rvcMask_14,
  output        io_rdata_1_rvcMask_15,
  input         io_wen_0,
  input  [5:0]  io_waddr_0,
  input         io_wdata_0_brMask_0,
  input         io_wdata_0_brMask_1,
  input         io_wdata_0_brMask_2,
  input         io_wdata_0_brMask_3,
  input         io_wdata_0_brMask_4,
  input         io_wdata_0_brMask_5,
  input         io_wdata_0_brMask_6,
  input         io_wdata_0_brMask_7,
  input         io_wdata_0_brMask_8,
  input         io_wdata_0_brMask_9,
  input         io_wdata_0_brMask_10,
  input         io_wdata_0_brMask_11,
  input         io_wdata_0_brMask_12,
  input         io_wdata_0_brMask_13,
  input         io_wdata_0_brMask_14,
  input         io_wdata_0_brMask_15,
  input         io_wdata_0_jmpInfo_valid,
  input         io_wdata_0_jmpInfo_bits_0,
  input         io_wdata_0_jmpInfo_bits_1,
  input         io_wdata_0_jmpInfo_bits_2,
  input  [3:0]  io_wdata_0_jmpOffset,
  input  [49:0] io_wdata_0_jalTarget,
  input         io_wdata_0_rvcMask_0,
  input         io_wdata_0_rvcMask_1,
  input         io_wdata_0_rvcMask_2,
  input         io_wdata_0_rvcMask_3,
  input         io_wdata_0_rvcMask_4,
  input         io_wdata_0_rvcMask_5,
  input         io_wdata_0_rvcMask_6,
  input         io_wdata_0_rvcMask_7,
  input         io_wdata_0_rvcMask_8,
  input         io_wdata_0_rvcMask_9,
  input         io_wdata_0_rvcMask_10,
  input         io_wdata_0_rvcMask_11,
  input         io_wdata_0_rvcMask_12,
  input         io_wdata_0_rvcMask_13,
  input         io_wdata_0_rvcMask_14,
  input         io_wdata_0_rvcMask_15
);

  wire        _dataBanks_3_io_rdata_0_brMask_0;
  wire        _dataBanks_3_io_rdata_0_brMask_1;
  wire        _dataBanks_3_io_rdata_0_brMask_2;
  wire        _dataBanks_3_io_rdata_0_brMask_3;
  wire        _dataBanks_3_io_rdata_0_brMask_4;
  wire        _dataBanks_3_io_rdata_0_brMask_5;
  wire        _dataBanks_3_io_rdata_0_brMask_6;
  wire        _dataBanks_3_io_rdata_0_brMask_7;
  wire        _dataBanks_3_io_rdata_0_brMask_8;
  wire        _dataBanks_3_io_rdata_0_brMask_9;
  wire        _dataBanks_3_io_rdata_0_brMask_10;
  wire        _dataBanks_3_io_rdata_0_brMask_11;
  wire        _dataBanks_3_io_rdata_0_brMask_12;
  wire        _dataBanks_3_io_rdata_0_brMask_13;
  wire        _dataBanks_3_io_rdata_0_brMask_14;
  wire        _dataBanks_3_io_rdata_0_brMask_15;
  wire        _dataBanks_3_io_rdata_0_jmpInfo_valid;
  wire        _dataBanks_3_io_rdata_0_jmpInfo_bits_0;
  wire        _dataBanks_3_io_rdata_0_jmpInfo_bits_1;
  wire        _dataBanks_3_io_rdata_0_jmpInfo_bits_2;
  wire [3:0]  _dataBanks_3_io_rdata_0_jmpOffset;
  wire        _dataBanks_3_io_rdata_0_rvcMask_0;
  wire        _dataBanks_3_io_rdata_0_rvcMask_1;
  wire        _dataBanks_3_io_rdata_0_rvcMask_2;
  wire        _dataBanks_3_io_rdata_0_rvcMask_3;
  wire        _dataBanks_3_io_rdata_0_rvcMask_4;
  wire        _dataBanks_3_io_rdata_0_rvcMask_5;
  wire        _dataBanks_3_io_rdata_0_rvcMask_6;
  wire        _dataBanks_3_io_rdata_0_rvcMask_7;
  wire        _dataBanks_3_io_rdata_0_rvcMask_8;
  wire        _dataBanks_3_io_rdata_0_rvcMask_9;
  wire        _dataBanks_3_io_rdata_0_rvcMask_10;
  wire        _dataBanks_3_io_rdata_0_rvcMask_11;
  wire        _dataBanks_3_io_rdata_0_rvcMask_12;
  wire        _dataBanks_3_io_rdata_0_rvcMask_13;
  wire        _dataBanks_3_io_rdata_0_rvcMask_14;
  wire        _dataBanks_3_io_rdata_0_rvcMask_15;
  wire        _dataBanks_3_io_rdata_1_brMask_0;
  wire        _dataBanks_3_io_rdata_1_brMask_1;
  wire        _dataBanks_3_io_rdata_1_brMask_2;
  wire        _dataBanks_3_io_rdata_1_brMask_3;
  wire        _dataBanks_3_io_rdata_1_brMask_4;
  wire        _dataBanks_3_io_rdata_1_brMask_5;
  wire        _dataBanks_3_io_rdata_1_brMask_6;
  wire        _dataBanks_3_io_rdata_1_brMask_7;
  wire        _dataBanks_3_io_rdata_1_brMask_8;
  wire        _dataBanks_3_io_rdata_1_brMask_9;
  wire        _dataBanks_3_io_rdata_1_brMask_10;
  wire        _dataBanks_3_io_rdata_1_brMask_11;
  wire        _dataBanks_3_io_rdata_1_brMask_12;
  wire        _dataBanks_3_io_rdata_1_brMask_13;
  wire        _dataBanks_3_io_rdata_1_brMask_14;
  wire        _dataBanks_3_io_rdata_1_brMask_15;
  wire        _dataBanks_3_io_rdata_1_jmpInfo_valid;
  wire        _dataBanks_3_io_rdata_1_jmpInfo_bits_0;
  wire        _dataBanks_3_io_rdata_1_jmpInfo_bits_1;
  wire        _dataBanks_3_io_rdata_1_jmpInfo_bits_2;
  wire [3:0]  _dataBanks_3_io_rdata_1_jmpOffset;
  wire [49:0] _dataBanks_3_io_rdata_1_jalTarget;
  wire        _dataBanks_3_io_rdata_1_rvcMask_0;
  wire        _dataBanks_3_io_rdata_1_rvcMask_1;
  wire        _dataBanks_3_io_rdata_1_rvcMask_2;
  wire        _dataBanks_3_io_rdata_1_rvcMask_3;
  wire        _dataBanks_3_io_rdata_1_rvcMask_4;
  wire        _dataBanks_3_io_rdata_1_rvcMask_5;
  wire        _dataBanks_3_io_rdata_1_rvcMask_6;
  wire        _dataBanks_3_io_rdata_1_rvcMask_7;
  wire        _dataBanks_3_io_rdata_1_rvcMask_8;
  wire        _dataBanks_3_io_rdata_1_rvcMask_9;
  wire        _dataBanks_3_io_rdata_1_rvcMask_10;
  wire        _dataBanks_3_io_rdata_1_rvcMask_11;
  wire        _dataBanks_3_io_rdata_1_rvcMask_12;
  wire        _dataBanks_3_io_rdata_1_rvcMask_13;
  wire        _dataBanks_3_io_rdata_1_rvcMask_14;
  wire        _dataBanks_3_io_rdata_1_rvcMask_15;
  wire        _dataBanks_2_io_rdata_0_brMask_0;
  wire        _dataBanks_2_io_rdata_0_brMask_1;
  wire        _dataBanks_2_io_rdata_0_brMask_2;
  wire        _dataBanks_2_io_rdata_0_brMask_3;
  wire        _dataBanks_2_io_rdata_0_brMask_4;
  wire        _dataBanks_2_io_rdata_0_brMask_5;
  wire        _dataBanks_2_io_rdata_0_brMask_6;
  wire        _dataBanks_2_io_rdata_0_brMask_7;
  wire        _dataBanks_2_io_rdata_0_brMask_8;
  wire        _dataBanks_2_io_rdata_0_brMask_9;
  wire        _dataBanks_2_io_rdata_0_brMask_10;
  wire        _dataBanks_2_io_rdata_0_brMask_11;
  wire        _dataBanks_2_io_rdata_0_brMask_12;
  wire        _dataBanks_2_io_rdata_0_brMask_13;
  wire        _dataBanks_2_io_rdata_0_brMask_14;
  wire        _dataBanks_2_io_rdata_0_brMask_15;
  wire        _dataBanks_2_io_rdata_0_jmpInfo_valid;
  wire        _dataBanks_2_io_rdata_0_jmpInfo_bits_0;
  wire        _dataBanks_2_io_rdata_0_jmpInfo_bits_1;
  wire        _dataBanks_2_io_rdata_0_jmpInfo_bits_2;
  wire [3:0]  _dataBanks_2_io_rdata_0_jmpOffset;
  wire        _dataBanks_2_io_rdata_0_rvcMask_0;
  wire        _dataBanks_2_io_rdata_0_rvcMask_1;
  wire        _dataBanks_2_io_rdata_0_rvcMask_2;
  wire        _dataBanks_2_io_rdata_0_rvcMask_3;
  wire        _dataBanks_2_io_rdata_0_rvcMask_4;
  wire        _dataBanks_2_io_rdata_0_rvcMask_5;
  wire        _dataBanks_2_io_rdata_0_rvcMask_6;
  wire        _dataBanks_2_io_rdata_0_rvcMask_7;
  wire        _dataBanks_2_io_rdata_0_rvcMask_8;
  wire        _dataBanks_2_io_rdata_0_rvcMask_9;
  wire        _dataBanks_2_io_rdata_0_rvcMask_10;
  wire        _dataBanks_2_io_rdata_0_rvcMask_11;
  wire        _dataBanks_2_io_rdata_0_rvcMask_12;
  wire        _dataBanks_2_io_rdata_0_rvcMask_13;
  wire        _dataBanks_2_io_rdata_0_rvcMask_14;
  wire        _dataBanks_2_io_rdata_0_rvcMask_15;
  wire        _dataBanks_2_io_rdata_1_brMask_0;
  wire        _dataBanks_2_io_rdata_1_brMask_1;
  wire        _dataBanks_2_io_rdata_1_brMask_2;
  wire        _dataBanks_2_io_rdata_1_brMask_3;
  wire        _dataBanks_2_io_rdata_1_brMask_4;
  wire        _dataBanks_2_io_rdata_1_brMask_5;
  wire        _dataBanks_2_io_rdata_1_brMask_6;
  wire        _dataBanks_2_io_rdata_1_brMask_7;
  wire        _dataBanks_2_io_rdata_1_brMask_8;
  wire        _dataBanks_2_io_rdata_1_brMask_9;
  wire        _dataBanks_2_io_rdata_1_brMask_10;
  wire        _dataBanks_2_io_rdata_1_brMask_11;
  wire        _dataBanks_2_io_rdata_1_brMask_12;
  wire        _dataBanks_2_io_rdata_1_brMask_13;
  wire        _dataBanks_2_io_rdata_1_brMask_14;
  wire        _dataBanks_2_io_rdata_1_brMask_15;
  wire        _dataBanks_2_io_rdata_1_jmpInfo_valid;
  wire        _dataBanks_2_io_rdata_1_jmpInfo_bits_0;
  wire        _dataBanks_2_io_rdata_1_jmpInfo_bits_1;
  wire        _dataBanks_2_io_rdata_1_jmpInfo_bits_2;
  wire [3:0]  _dataBanks_2_io_rdata_1_jmpOffset;
  wire [49:0] _dataBanks_2_io_rdata_1_jalTarget;
  wire        _dataBanks_2_io_rdata_1_rvcMask_0;
  wire        _dataBanks_2_io_rdata_1_rvcMask_1;
  wire        _dataBanks_2_io_rdata_1_rvcMask_2;
  wire        _dataBanks_2_io_rdata_1_rvcMask_3;
  wire        _dataBanks_2_io_rdata_1_rvcMask_4;
  wire        _dataBanks_2_io_rdata_1_rvcMask_5;
  wire        _dataBanks_2_io_rdata_1_rvcMask_6;
  wire        _dataBanks_2_io_rdata_1_rvcMask_7;
  wire        _dataBanks_2_io_rdata_1_rvcMask_8;
  wire        _dataBanks_2_io_rdata_1_rvcMask_9;
  wire        _dataBanks_2_io_rdata_1_rvcMask_10;
  wire        _dataBanks_2_io_rdata_1_rvcMask_11;
  wire        _dataBanks_2_io_rdata_1_rvcMask_12;
  wire        _dataBanks_2_io_rdata_1_rvcMask_13;
  wire        _dataBanks_2_io_rdata_1_rvcMask_14;
  wire        _dataBanks_2_io_rdata_1_rvcMask_15;
  wire        _dataBanks_1_io_rdata_0_brMask_0;
  wire        _dataBanks_1_io_rdata_0_brMask_1;
  wire        _dataBanks_1_io_rdata_0_brMask_2;
  wire        _dataBanks_1_io_rdata_0_brMask_3;
  wire        _dataBanks_1_io_rdata_0_brMask_4;
  wire        _dataBanks_1_io_rdata_0_brMask_5;
  wire        _dataBanks_1_io_rdata_0_brMask_6;
  wire        _dataBanks_1_io_rdata_0_brMask_7;
  wire        _dataBanks_1_io_rdata_0_brMask_8;
  wire        _dataBanks_1_io_rdata_0_brMask_9;
  wire        _dataBanks_1_io_rdata_0_brMask_10;
  wire        _dataBanks_1_io_rdata_0_brMask_11;
  wire        _dataBanks_1_io_rdata_0_brMask_12;
  wire        _dataBanks_1_io_rdata_0_brMask_13;
  wire        _dataBanks_1_io_rdata_0_brMask_14;
  wire        _dataBanks_1_io_rdata_0_brMask_15;
  wire        _dataBanks_1_io_rdata_0_jmpInfo_valid;
  wire        _dataBanks_1_io_rdata_0_jmpInfo_bits_0;
  wire        _dataBanks_1_io_rdata_0_jmpInfo_bits_1;
  wire        _dataBanks_1_io_rdata_0_jmpInfo_bits_2;
  wire [3:0]  _dataBanks_1_io_rdata_0_jmpOffset;
  wire        _dataBanks_1_io_rdata_0_rvcMask_0;
  wire        _dataBanks_1_io_rdata_0_rvcMask_1;
  wire        _dataBanks_1_io_rdata_0_rvcMask_2;
  wire        _dataBanks_1_io_rdata_0_rvcMask_3;
  wire        _dataBanks_1_io_rdata_0_rvcMask_4;
  wire        _dataBanks_1_io_rdata_0_rvcMask_5;
  wire        _dataBanks_1_io_rdata_0_rvcMask_6;
  wire        _dataBanks_1_io_rdata_0_rvcMask_7;
  wire        _dataBanks_1_io_rdata_0_rvcMask_8;
  wire        _dataBanks_1_io_rdata_0_rvcMask_9;
  wire        _dataBanks_1_io_rdata_0_rvcMask_10;
  wire        _dataBanks_1_io_rdata_0_rvcMask_11;
  wire        _dataBanks_1_io_rdata_0_rvcMask_12;
  wire        _dataBanks_1_io_rdata_0_rvcMask_13;
  wire        _dataBanks_1_io_rdata_0_rvcMask_14;
  wire        _dataBanks_1_io_rdata_0_rvcMask_15;
  wire        _dataBanks_1_io_rdata_1_brMask_0;
  wire        _dataBanks_1_io_rdata_1_brMask_1;
  wire        _dataBanks_1_io_rdata_1_brMask_2;
  wire        _dataBanks_1_io_rdata_1_brMask_3;
  wire        _dataBanks_1_io_rdata_1_brMask_4;
  wire        _dataBanks_1_io_rdata_1_brMask_5;
  wire        _dataBanks_1_io_rdata_1_brMask_6;
  wire        _dataBanks_1_io_rdata_1_brMask_7;
  wire        _dataBanks_1_io_rdata_1_brMask_8;
  wire        _dataBanks_1_io_rdata_1_brMask_9;
  wire        _dataBanks_1_io_rdata_1_brMask_10;
  wire        _dataBanks_1_io_rdata_1_brMask_11;
  wire        _dataBanks_1_io_rdata_1_brMask_12;
  wire        _dataBanks_1_io_rdata_1_brMask_13;
  wire        _dataBanks_1_io_rdata_1_brMask_14;
  wire        _dataBanks_1_io_rdata_1_brMask_15;
  wire        _dataBanks_1_io_rdata_1_jmpInfo_valid;
  wire        _dataBanks_1_io_rdata_1_jmpInfo_bits_0;
  wire        _dataBanks_1_io_rdata_1_jmpInfo_bits_1;
  wire        _dataBanks_1_io_rdata_1_jmpInfo_bits_2;
  wire [3:0]  _dataBanks_1_io_rdata_1_jmpOffset;
  wire [49:0] _dataBanks_1_io_rdata_1_jalTarget;
  wire        _dataBanks_1_io_rdata_1_rvcMask_0;
  wire        _dataBanks_1_io_rdata_1_rvcMask_1;
  wire        _dataBanks_1_io_rdata_1_rvcMask_2;
  wire        _dataBanks_1_io_rdata_1_rvcMask_3;
  wire        _dataBanks_1_io_rdata_1_rvcMask_4;
  wire        _dataBanks_1_io_rdata_1_rvcMask_5;
  wire        _dataBanks_1_io_rdata_1_rvcMask_6;
  wire        _dataBanks_1_io_rdata_1_rvcMask_7;
  wire        _dataBanks_1_io_rdata_1_rvcMask_8;
  wire        _dataBanks_1_io_rdata_1_rvcMask_9;
  wire        _dataBanks_1_io_rdata_1_rvcMask_10;
  wire        _dataBanks_1_io_rdata_1_rvcMask_11;
  wire        _dataBanks_1_io_rdata_1_rvcMask_12;
  wire        _dataBanks_1_io_rdata_1_rvcMask_13;
  wire        _dataBanks_1_io_rdata_1_rvcMask_14;
  wire        _dataBanks_1_io_rdata_1_rvcMask_15;
  wire        _dataBanks_0_io_rdata_0_brMask_0;
  wire        _dataBanks_0_io_rdata_0_brMask_1;
  wire        _dataBanks_0_io_rdata_0_brMask_2;
  wire        _dataBanks_0_io_rdata_0_brMask_3;
  wire        _dataBanks_0_io_rdata_0_brMask_4;
  wire        _dataBanks_0_io_rdata_0_brMask_5;
  wire        _dataBanks_0_io_rdata_0_brMask_6;
  wire        _dataBanks_0_io_rdata_0_brMask_7;
  wire        _dataBanks_0_io_rdata_0_brMask_8;
  wire        _dataBanks_0_io_rdata_0_brMask_9;
  wire        _dataBanks_0_io_rdata_0_brMask_10;
  wire        _dataBanks_0_io_rdata_0_brMask_11;
  wire        _dataBanks_0_io_rdata_0_brMask_12;
  wire        _dataBanks_0_io_rdata_0_brMask_13;
  wire        _dataBanks_0_io_rdata_0_brMask_14;
  wire        _dataBanks_0_io_rdata_0_brMask_15;
  wire        _dataBanks_0_io_rdata_0_jmpInfo_valid;
  wire        _dataBanks_0_io_rdata_0_jmpInfo_bits_0;
  wire        _dataBanks_0_io_rdata_0_jmpInfo_bits_1;
  wire        _dataBanks_0_io_rdata_0_jmpInfo_bits_2;
  wire [3:0]  _dataBanks_0_io_rdata_0_jmpOffset;
  wire        _dataBanks_0_io_rdata_0_rvcMask_0;
  wire        _dataBanks_0_io_rdata_0_rvcMask_1;
  wire        _dataBanks_0_io_rdata_0_rvcMask_2;
  wire        _dataBanks_0_io_rdata_0_rvcMask_3;
  wire        _dataBanks_0_io_rdata_0_rvcMask_4;
  wire        _dataBanks_0_io_rdata_0_rvcMask_5;
  wire        _dataBanks_0_io_rdata_0_rvcMask_6;
  wire        _dataBanks_0_io_rdata_0_rvcMask_7;
  wire        _dataBanks_0_io_rdata_0_rvcMask_8;
  wire        _dataBanks_0_io_rdata_0_rvcMask_9;
  wire        _dataBanks_0_io_rdata_0_rvcMask_10;
  wire        _dataBanks_0_io_rdata_0_rvcMask_11;
  wire        _dataBanks_0_io_rdata_0_rvcMask_12;
  wire        _dataBanks_0_io_rdata_0_rvcMask_13;
  wire        _dataBanks_0_io_rdata_0_rvcMask_14;
  wire        _dataBanks_0_io_rdata_0_rvcMask_15;
  wire        _dataBanks_0_io_rdata_1_brMask_0;
  wire        _dataBanks_0_io_rdata_1_brMask_1;
  wire        _dataBanks_0_io_rdata_1_brMask_2;
  wire        _dataBanks_0_io_rdata_1_brMask_3;
  wire        _dataBanks_0_io_rdata_1_brMask_4;
  wire        _dataBanks_0_io_rdata_1_brMask_5;
  wire        _dataBanks_0_io_rdata_1_brMask_6;
  wire        _dataBanks_0_io_rdata_1_brMask_7;
  wire        _dataBanks_0_io_rdata_1_brMask_8;
  wire        _dataBanks_0_io_rdata_1_brMask_9;
  wire        _dataBanks_0_io_rdata_1_brMask_10;
  wire        _dataBanks_0_io_rdata_1_brMask_11;
  wire        _dataBanks_0_io_rdata_1_brMask_12;
  wire        _dataBanks_0_io_rdata_1_brMask_13;
  wire        _dataBanks_0_io_rdata_1_brMask_14;
  wire        _dataBanks_0_io_rdata_1_brMask_15;
  wire        _dataBanks_0_io_rdata_1_jmpInfo_valid;
  wire        _dataBanks_0_io_rdata_1_jmpInfo_bits_0;
  wire        _dataBanks_0_io_rdata_1_jmpInfo_bits_1;
  wire        _dataBanks_0_io_rdata_1_jmpInfo_bits_2;
  wire [3:0]  _dataBanks_0_io_rdata_1_jmpOffset;
  wire [49:0] _dataBanks_0_io_rdata_1_jalTarget;
  wire        _dataBanks_0_io_rdata_1_rvcMask_0;
  wire        _dataBanks_0_io_rdata_1_rvcMask_1;
  wire        _dataBanks_0_io_rdata_1_rvcMask_2;
  wire        _dataBanks_0_io_rdata_1_rvcMask_3;
  wire        _dataBanks_0_io_rdata_1_rvcMask_4;
  wire        _dataBanks_0_io_rdata_1_rvcMask_5;
  wire        _dataBanks_0_io_rdata_1_rvcMask_6;
  wire        _dataBanks_0_io_rdata_1_rvcMask_7;
  wire        _dataBanks_0_io_rdata_1_rvcMask_8;
  wire        _dataBanks_0_io_rdata_1_rvcMask_9;
  wire        _dataBanks_0_io_rdata_1_rvcMask_10;
  wire        _dataBanks_0_io_rdata_1_rvcMask_11;
  wire        _dataBanks_0_io_rdata_1_rvcMask_12;
  wire        _dataBanks_0_io_rdata_1_rvcMask_13;
  wire        _dataBanks_0_io_rdata_1_rvcMask_14;
  wire        _dataBanks_0_io_rdata_1_rvcMask_15;
  reg  [5:0]  raddr_dup_0;
  reg  [5:0]  raddr_dup_1;
  reg         wen_dup_last_REG;
  reg  [5:0]  waddr_dup_0;
  reg         r_brMask_0;
  reg         r_brMask_1;
  reg         r_brMask_2;
  reg         r_brMask_3;
  reg         r_brMask_4;
  reg         r_brMask_5;
  reg         r_brMask_6;
  reg         r_brMask_7;
  reg         r_brMask_8;
  reg         r_brMask_9;
  reg         r_brMask_10;
  reg         r_brMask_11;
  reg         r_brMask_12;
  reg         r_brMask_13;
  reg         r_brMask_14;
  reg         r_brMask_15;
  reg         r_jmpInfo_valid;
  reg         r_jmpInfo_bits_0;
  reg         r_jmpInfo_bits_1;
  reg         r_jmpInfo_bits_2;
  reg  [3:0]  r_jmpOffset;
  reg  [49:0] r_jalTarget;
  reg         r_rvcMask_0;
  reg         r_rvcMask_1;
  reg         r_rvcMask_2;
  reg         r_rvcMask_3;
  reg         r_rvcMask_4;
  reg         r_rvcMask_5;
  reg         r_rvcMask_6;
  reg         r_rvcMask_7;
  reg         r_rvcMask_8;
  reg         r_rvcMask_9;
  reg         r_rvcMask_10;
  reg         r_rvcMask_11;
  reg         r_rvcMask_12;
  reg         r_rvcMask_13;
  reg         r_rvcMask_14;
  reg         r_rvcMask_15;
  reg  [5:0]  raddr_dup_0_1;
  reg  [5:0]  raddr_dup_1_1;
  reg         wen_dup_last_REG_1;
  reg  [5:0]  waddr_dup_0_1;
  reg         r_1_brMask_0;
  reg         r_1_brMask_1;
  reg         r_1_brMask_2;
  reg         r_1_brMask_3;
  reg         r_1_brMask_4;
  reg         r_1_brMask_5;
  reg         r_1_brMask_6;
  reg         r_1_brMask_7;
  reg         r_1_brMask_8;
  reg         r_1_brMask_9;
  reg         r_1_brMask_10;
  reg         r_1_brMask_11;
  reg         r_1_brMask_12;
  reg         r_1_brMask_13;
  reg         r_1_brMask_14;
  reg         r_1_brMask_15;
  reg         r_1_jmpInfo_valid;
  reg         r_1_jmpInfo_bits_0;
  reg         r_1_jmpInfo_bits_1;
  reg         r_1_jmpInfo_bits_2;
  reg  [3:0]  r_1_jmpOffset;
  reg  [49:0] r_1_jalTarget;
  reg         r_1_rvcMask_0;
  reg         r_1_rvcMask_1;
  reg         r_1_rvcMask_2;
  reg         r_1_rvcMask_3;
  reg         r_1_rvcMask_4;
  reg         r_1_rvcMask_5;
  reg         r_1_rvcMask_6;
  reg         r_1_rvcMask_7;
  reg         r_1_rvcMask_8;
  reg         r_1_rvcMask_9;
  reg         r_1_rvcMask_10;
  reg         r_1_rvcMask_11;
  reg         r_1_rvcMask_12;
  reg         r_1_rvcMask_13;
  reg         r_1_rvcMask_14;
  reg         r_1_rvcMask_15;
  reg  [5:0]  raddr_dup_0_2;
  reg  [5:0]  raddr_dup_1_2;
  reg         wen_dup_last_REG_2;
  reg  [5:0]  waddr_dup_0_2;
  reg         r_2_brMask_0;
  reg         r_2_brMask_1;
  reg         r_2_brMask_2;
  reg         r_2_brMask_3;
  reg         r_2_brMask_4;
  reg         r_2_brMask_5;
  reg         r_2_brMask_6;
  reg         r_2_brMask_7;
  reg         r_2_brMask_8;
  reg         r_2_brMask_9;
  reg         r_2_brMask_10;
  reg         r_2_brMask_11;
  reg         r_2_brMask_12;
  reg         r_2_brMask_13;
  reg         r_2_brMask_14;
  reg         r_2_brMask_15;
  reg         r_2_jmpInfo_valid;
  reg         r_2_jmpInfo_bits_0;
  reg         r_2_jmpInfo_bits_1;
  reg         r_2_jmpInfo_bits_2;
  reg  [3:0]  r_2_jmpOffset;
  reg  [49:0] r_2_jalTarget;
  reg         r_2_rvcMask_0;
  reg         r_2_rvcMask_1;
  reg         r_2_rvcMask_2;
  reg         r_2_rvcMask_3;
  reg         r_2_rvcMask_4;
  reg         r_2_rvcMask_5;
  reg         r_2_rvcMask_6;
  reg         r_2_rvcMask_7;
  reg         r_2_rvcMask_8;
  reg         r_2_rvcMask_9;
  reg         r_2_rvcMask_10;
  reg         r_2_rvcMask_11;
  reg         r_2_rvcMask_12;
  reg         r_2_rvcMask_13;
  reg         r_2_rvcMask_14;
  reg         r_2_rvcMask_15;
  reg  [5:0]  raddr_dup_0_3;
  reg  [5:0]  raddr_dup_1_3;
  reg         wen_dup_last_REG_3;
  reg  [5:0]  waddr_dup_0_3;
  reg         r_3_brMask_0;
  reg         r_3_brMask_1;
  reg         r_3_brMask_2;
  reg         r_3_brMask_3;
  reg         r_3_brMask_4;
  reg         r_3_brMask_5;
  reg         r_3_brMask_6;
  reg         r_3_brMask_7;
  reg         r_3_brMask_8;
  reg         r_3_brMask_9;
  reg         r_3_brMask_10;
  reg         r_3_brMask_11;
  reg         r_3_brMask_12;
  reg         r_3_brMask_13;
  reg         r_3_brMask_14;
  reg         r_3_brMask_15;
  reg         r_3_jmpInfo_valid;
  reg         r_3_jmpInfo_bits_0;
  reg         r_3_jmpInfo_bits_1;
  reg         r_3_jmpInfo_bits_2;
  reg  [3:0]  r_3_jmpOffset;
  reg  [49:0] r_3_jalTarget;
  reg         r_3_rvcMask_0;
  reg         r_3_rvcMask_1;
  reg         r_3_rvcMask_2;
  reg         r_3_rvcMask_3;
  reg         r_3_rvcMask_4;
  reg         r_3_rvcMask_5;
  reg         r_3_rvcMask_6;
  reg         r_3_rvcMask_7;
  reg         r_3_rvcMask_8;
  reg         r_3_rvcMask_9;
  reg         r_3_rvcMask_10;
  reg         r_3_rvcMask_11;
  reg         r_3_rvcMask_12;
  reg         r_3_rvcMask_13;
  reg         r_3_rvcMask_14;
  reg         r_3_rvcMask_15;
  reg  [5:0]  raddr_dup;
  wire        _io_rdata_0_T = raddr_dup[5:4] == 2'h0;
  wire        _io_rdata_0_T_1 = raddr_dup[5:4] == 2'h1;
  wire        _io_rdata_0_T_2 = raddr_dup[5:4] == 2'h2;
  reg  [5:0]  raddr_dup_2;
  wire        _io_rdata_1_T = raddr_dup_2[5:4] == 2'h0;
  wire        _io_rdata_1_T_1 = raddr_dup_2[5:4] == 2'h1;
  wire        _io_rdata_1_T_2 = raddr_dup_2[5:4] == 2'h2;
  always @(posedge clock) begin
    if (io_ren_0) begin
      raddr_dup_0 <= io_raddr_0;
      raddr_dup_0_1 <= io_raddr_0;
      raddr_dup_0_2 <= io_raddr_0;
      raddr_dup_0_3 <= io_raddr_0;
      raddr_dup <= io_raddr_0;
    end
    if (io_ren_1) begin
      raddr_dup_1 <= io_raddr_1;
      raddr_dup_1_1 <= io_raddr_1;
      raddr_dup_1_2 <= io_raddr_1;
      raddr_dup_1_3 <= io_raddr_1;
      raddr_dup_2 <= io_raddr_1;
    end
    if (io_wen_0) begin
      waddr_dup_0 <= io_waddr_0;
      r_brMask_0 <= io_wdata_0_brMask_0;
      r_brMask_1 <= io_wdata_0_brMask_1;
      r_brMask_2 <= io_wdata_0_brMask_2;
      r_brMask_3 <= io_wdata_0_brMask_3;
      r_brMask_4 <= io_wdata_0_brMask_4;
      r_brMask_5 <= io_wdata_0_brMask_5;
      r_brMask_6 <= io_wdata_0_brMask_6;
      r_brMask_7 <= io_wdata_0_brMask_7;
      r_brMask_8 <= io_wdata_0_brMask_8;
      r_brMask_9 <= io_wdata_0_brMask_9;
      r_brMask_10 <= io_wdata_0_brMask_10;
      r_brMask_11 <= io_wdata_0_brMask_11;
      r_brMask_12 <= io_wdata_0_brMask_12;
      r_brMask_13 <= io_wdata_0_brMask_13;
      r_brMask_14 <= io_wdata_0_brMask_14;
      r_brMask_15 <= io_wdata_0_brMask_15;
      r_jmpInfo_valid <= io_wdata_0_jmpInfo_valid;
      r_jmpInfo_bits_0 <= io_wdata_0_jmpInfo_bits_0;
      r_jmpInfo_bits_1 <= io_wdata_0_jmpInfo_bits_1;
      r_jmpInfo_bits_2 <= io_wdata_0_jmpInfo_bits_2;
      r_jmpOffset <= io_wdata_0_jmpOffset;
      r_jalTarget <= io_wdata_0_jalTarget;
      r_rvcMask_0 <= io_wdata_0_rvcMask_0;
      r_rvcMask_1 <= io_wdata_0_rvcMask_1;
      r_rvcMask_2 <= io_wdata_0_rvcMask_2;
      r_rvcMask_3 <= io_wdata_0_rvcMask_3;
      r_rvcMask_4 <= io_wdata_0_rvcMask_4;
      r_rvcMask_5 <= io_wdata_0_rvcMask_5;
      r_rvcMask_6 <= io_wdata_0_rvcMask_6;
      r_rvcMask_7 <= io_wdata_0_rvcMask_7;
      r_rvcMask_8 <= io_wdata_0_rvcMask_8;
      r_rvcMask_9 <= io_wdata_0_rvcMask_9;
      r_rvcMask_10 <= io_wdata_0_rvcMask_10;
      r_rvcMask_11 <= io_wdata_0_rvcMask_11;
      r_rvcMask_12 <= io_wdata_0_rvcMask_12;
      r_rvcMask_13 <= io_wdata_0_rvcMask_13;
      r_rvcMask_14 <= io_wdata_0_rvcMask_14;
      r_rvcMask_15 <= io_wdata_0_rvcMask_15;
      waddr_dup_0_1 <= io_waddr_0;
      r_1_brMask_0 <= io_wdata_0_brMask_0;
      r_1_brMask_1 <= io_wdata_0_brMask_1;
      r_1_brMask_2 <= io_wdata_0_brMask_2;
      r_1_brMask_3 <= io_wdata_0_brMask_3;
      r_1_brMask_4 <= io_wdata_0_brMask_4;
      r_1_brMask_5 <= io_wdata_0_brMask_5;
      r_1_brMask_6 <= io_wdata_0_brMask_6;
      r_1_brMask_7 <= io_wdata_0_brMask_7;
      r_1_brMask_8 <= io_wdata_0_brMask_8;
      r_1_brMask_9 <= io_wdata_0_brMask_9;
      r_1_brMask_10 <= io_wdata_0_brMask_10;
      r_1_brMask_11 <= io_wdata_0_brMask_11;
      r_1_brMask_12 <= io_wdata_0_brMask_12;
      r_1_brMask_13 <= io_wdata_0_brMask_13;
      r_1_brMask_14 <= io_wdata_0_brMask_14;
      r_1_brMask_15 <= io_wdata_0_brMask_15;
      r_1_jmpInfo_valid <= io_wdata_0_jmpInfo_valid;
      r_1_jmpInfo_bits_0 <= io_wdata_0_jmpInfo_bits_0;
      r_1_jmpInfo_bits_1 <= io_wdata_0_jmpInfo_bits_1;
      r_1_jmpInfo_bits_2 <= io_wdata_0_jmpInfo_bits_2;
      r_1_jmpOffset <= io_wdata_0_jmpOffset;
      r_1_jalTarget <= io_wdata_0_jalTarget;
      r_1_rvcMask_0 <= io_wdata_0_rvcMask_0;
      r_1_rvcMask_1 <= io_wdata_0_rvcMask_1;
      r_1_rvcMask_2 <= io_wdata_0_rvcMask_2;
      r_1_rvcMask_3 <= io_wdata_0_rvcMask_3;
      r_1_rvcMask_4 <= io_wdata_0_rvcMask_4;
      r_1_rvcMask_5 <= io_wdata_0_rvcMask_5;
      r_1_rvcMask_6 <= io_wdata_0_rvcMask_6;
      r_1_rvcMask_7 <= io_wdata_0_rvcMask_7;
      r_1_rvcMask_8 <= io_wdata_0_rvcMask_8;
      r_1_rvcMask_9 <= io_wdata_0_rvcMask_9;
      r_1_rvcMask_10 <= io_wdata_0_rvcMask_10;
      r_1_rvcMask_11 <= io_wdata_0_rvcMask_11;
      r_1_rvcMask_12 <= io_wdata_0_rvcMask_12;
      r_1_rvcMask_13 <= io_wdata_0_rvcMask_13;
      r_1_rvcMask_14 <= io_wdata_0_rvcMask_14;
      r_1_rvcMask_15 <= io_wdata_0_rvcMask_15;
      waddr_dup_0_2 <= io_waddr_0;
      r_2_brMask_0 <= io_wdata_0_brMask_0;
      r_2_brMask_1 <= io_wdata_0_brMask_1;
      r_2_brMask_2 <= io_wdata_0_brMask_2;
      r_2_brMask_3 <= io_wdata_0_brMask_3;
      r_2_brMask_4 <= io_wdata_0_brMask_4;
      r_2_brMask_5 <= io_wdata_0_brMask_5;
      r_2_brMask_6 <= io_wdata_0_brMask_6;
      r_2_brMask_7 <= io_wdata_0_brMask_7;
      r_2_brMask_8 <= io_wdata_0_brMask_8;
      r_2_brMask_9 <= io_wdata_0_brMask_9;
      r_2_brMask_10 <= io_wdata_0_brMask_10;
      r_2_brMask_11 <= io_wdata_0_brMask_11;
      r_2_brMask_12 <= io_wdata_0_brMask_12;
      r_2_brMask_13 <= io_wdata_0_brMask_13;
      r_2_brMask_14 <= io_wdata_0_brMask_14;
      r_2_brMask_15 <= io_wdata_0_brMask_15;
      r_2_jmpInfo_valid <= io_wdata_0_jmpInfo_valid;
      r_2_jmpInfo_bits_0 <= io_wdata_0_jmpInfo_bits_0;
      r_2_jmpInfo_bits_1 <= io_wdata_0_jmpInfo_bits_1;
      r_2_jmpInfo_bits_2 <= io_wdata_0_jmpInfo_bits_2;
      r_2_jmpOffset <= io_wdata_0_jmpOffset;
      r_2_jalTarget <= io_wdata_0_jalTarget;
      r_2_rvcMask_0 <= io_wdata_0_rvcMask_0;
      r_2_rvcMask_1 <= io_wdata_0_rvcMask_1;
      r_2_rvcMask_2 <= io_wdata_0_rvcMask_2;
      r_2_rvcMask_3 <= io_wdata_0_rvcMask_3;
      r_2_rvcMask_4 <= io_wdata_0_rvcMask_4;
      r_2_rvcMask_5 <= io_wdata_0_rvcMask_5;
      r_2_rvcMask_6 <= io_wdata_0_rvcMask_6;
      r_2_rvcMask_7 <= io_wdata_0_rvcMask_7;
      r_2_rvcMask_8 <= io_wdata_0_rvcMask_8;
      r_2_rvcMask_9 <= io_wdata_0_rvcMask_9;
      r_2_rvcMask_10 <= io_wdata_0_rvcMask_10;
      r_2_rvcMask_11 <= io_wdata_0_rvcMask_11;
      r_2_rvcMask_12 <= io_wdata_0_rvcMask_12;
      r_2_rvcMask_13 <= io_wdata_0_rvcMask_13;
      r_2_rvcMask_14 <= io_wdata_0_rvcMask_14;
      r_2_rvcMask_15 <= io_wdata_0_rvcMask_15;
      waddr_dup_0_3 <= io_waddr_0;
      r_3_brMask_0 <= io_wdata_0_brMask_0;
      r_3_brMask_1 <= io_wdata_0_brMask_1;
      r_3_brMask_2 <= io_wdata_0_brMask_2;
      r_3_brMask_3 <= io_wdata_0_brMask_3;
      r_3_brMask_4 <= io_wdata_0_brMask_4;
      r_3_brMask_5 <= io_wdata_0_brMask_5;
      r_3_brMask_6 <= io_wdata_0_brMask_6;
      r_3_brMask_7 <= io_wdata_0_brMask_7;
      r_3_brMask_8 <= io_wdata_0_brMask_8;
      r_3_brMask_9 <= io_wdata_0_brMask_9;
      r_3_brMask_10 <= io_wdata_0_brMask_10;
      r_3_brMask_11 <= io_wdata_0_brMask_11;
      r_3_brMask_12 <= io_wdata_0_brMask_12;
      r_3_brMask_13 <= io_wdata_0_brMask_13;
      r_3_brMask_14 <= io_wdata_0_brMask_14;
      r_3_brMask_15 <= io_wdata_0_brMask_15;
      r_3_jmpInfo_valid <= io_wdata_0_jmpInfo_valid;
      r_3_jmpInfo_bits_0 <= io_wdata_0_jmpInfo_bits_0;
      r_3_jmpInfo_bits_1 <= io_wdata_0_jmpInfo_bits_1;
      r_3_jmpInfo_bits_2 <= io_wdata_0_jmpInfo_bits_2;
      r_3_jmpOffset <= io_wdata_0_jmpOffset;
      r_3_jalTarget <= io_wdata_0_jalTarget;
      r_3_rvcMask_0 <= io_wdata_0_rvcMask_0;
      r_3_rvcMask_1 <= io_wdata_0_rvcMask_1;
      r_3_rvcMask_2 <= io_wdata_0_rvcMask_2;
      r_3_rvcMask_3 <= io_wdata_0_rvcMask_3;
      r_3_rvcMask_4 <= io_wdata_0_rvcMask_4;
      r_3_rvcMask_5 <= io_wdata_0_rvcMask_5;
      r_3_rvcMask_6 <= io_wdata_0_rvcMask_6;
      r_3_rvcMask_7 <= io_wdata_0_rvcMask_7;
      r_3_rvcMask_8 <= io_wdata_0_rvcMask_8;
      r_3_rvcMask_9 <= io_wdata_0_rvcMask_9;
      r_3_rvcMask_10 <= io_wdata_0_rvcMask_10;
      r_3_rvcMask_11 <= io_wdata_0_rvcMask_11;
      r_3_rvcMask_12 <= io_wdata_0_rvcMask_12;
      r_3_rvcMask_13 <= io_wdata_0_rvcMask_13;
      r_3_rvcMask_14 <= io_wdata_0_rvcMask_14;
      r_3_rvcMask_15 <= io_wdata_0_rvcMask_15;
    end
  end // always @(posedge)
  always @(posedge clock or posedge reset) begin
    if (reset) begin
      wen_dup_last_REG <= 1'h0;
      wen_dup_last_REG_1 <= 1'h0;
      wen_dup_last_REG_2 <= 1'h0;
      wen_dup_last_REG_3 <= 1'h0;
    end
    else begin
      wen_dup_last_REG <= io_wen_0;
      wen_dup_last_REG_1 <= io_wen_0;
      wen_dup_last_REG_2 <= io_wen_0;
      wen_dup_last_REG_3 <= io_wen_0;
    end
  end // always @(posedge, posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:13];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        for (logic [3:0] i = 4'h0; i < 4'hE; i += 4'h1) begin
          _RANDOM[i] = `RANDOM;
        end
        raddr_dup_0 = _RANDOM[4'h0][5:0];
        raddr_dup_1 = _RANDOM[4'h0][11:6];
        wen_dup_last_REG = _RANDOM[4'h0][12];
        waddr_dup_0 = _RANDOM[4'h0][18:13];
        r_brMask_0 = _RANDOM[4'h0][19];
        r_brMask_1 = _RANDOM[4'h0][20];
        r_brMask_2 = _RANDOM[4'h0][21];
        r_brMask_3 = _RANDOM[4'h0][22];
        r_brMask_4 = _RANDOM[4'h0][23];
        r_brMask_5 = _RANDOM[4'h0][24];
        r_brMask_6 = _RANDOM[4'h0][25];
        r_brMask_7 = _RANDOM[4'h0][26];
        r_brMask_8 = _RANDOM[4'h0][27];
        r_brMask_9 = _RANDOM[4'h0][28];
        r_brMask_10 = _RANDOM[4'h0][29];
        r_brMask_11 = _RANDOM[4'h0][30];
        r_brMask_12 = _RANDOM[4'h0][31];
        r_brMask_13 = _RANDOM[4'h1][0];
        r_brMask_14 = _RANDOM[4'h1][1];
        r_brMask_15 = _RANDOM[4'h1][2];
        r_jmpInfo_valid = _RANDOM[4'h1][3];
        r_jmpInfo_bits_0 = _RANDOM[4'h1][4];
        r_jmpInfo_bits_1 = _RANDOM[4'h1][5];
        r_jmpInfo_bits_2 = _RANDOM[4'h1][6];
        r_jmpOffset = _RANDOM[4'h1][10:7];
        r_jalTarget = {_RANDOM[4'h1][31:11], _RANDOM[4'h2][28:0]};
        r_rvcMask_0 = _RANDOM[4'h2][29];
        r_rvcMask_1 = _RANDOM[4'h2][30];
        r_rvcMask_2 = _RANDOM[4'h2][31];
        r_rvcMask_3 = _RANDOM[4'h3][0];
        r_rvcMask_4 = _RANDOM[4'h3][1];
        r_rvcMask_5 = _RANDOM[4'h3][2];
        r_rvcMask_6 = _RANDOM[4'h3][3];
        r_rvcMask_7 = _RANDOM[4'h3][4];
        r_rvcMask_8 = _RANDOM[4'h3][5];
        r_rvcMask_9 = _RANDOM[4'h3][6];
        r_rvcMask_10 = _RANDOM[4'h3][7];
        r_rvcMask_11 = _RANDOM[4'h3][8];
        r_rvcMask_12 = _RANDOM[4'h3][9];
        r_rvcMask_13 = _RANDOM[4'h3][10];
        r_rvcMask_14 = _RANDOM[4'h3][11];
        r_rvcMask_15 = _RANDOM[4'h3][12];
        raddr_dup_0_1 = _RANDOM[4'h3][18:13];
        raddr_dup_1_1 = _RANDOM[4'h3][24:19];
        wen_dup_last_REG_1 = _RANDOM[4'h3][25];
        waddr_dup_0_1 = _RANDOM[4'h3][31:26];
        r_1_brMask_0 = _RANDOM[4'h4][0];
        r_1_brMask_1 = _RANDOM[4'h4][1];
        r_1_brMask_2 = _RANDOM[4'h4][2];
        r_1_brMask_3 = _RANDOM[4'h4][3];
        r_1_brMask_4 = _RANDOM[4'h4][4];
        r_1_brMask_5 = _RANDOM[4'h4][5];
        r_1_brMask_6 = _RANDOM[4'h4][6];
        r_1_brMask_7 = _RANDOM[4'h4][7];
        r_1_brMask_8 = _RANDOM[4'h4][8];
        r_1_brMask_9 = _RANDOM[4'h4][9];
        r_1_brMask_10 = _RANDOM[4'h4][10];
        r_1_brMask_11 = _RANDOM[4'h4][11];
        r_1_brMask_12 = _RANDOM[4'h4][12];
        r_1_brMask_13 = _RANDOM[4'h4][13];
        r_1_brMask_14 = _RANDOM[4'h4][14];
        r_1_brMask_15 = _RANDOM[4'h4][15];
        r_1_jmpInfo_valid = _RANDOM[4'h4][16];
        r_1_jmpInfo_bits_0 = _RANDOM[4'h4][17];
        r_1_jmpInfo_bits_1 = _RANDOM[4'h4][18];
        r_1_jmpInfo_bits_2 = _RANDOM[4'h4][19];
        r_1_jmpOffset = _RANDOM[4'h4][23:20];
        r_1_jalTarget = {_RANDOM[4'h4][31:24], _RANDOM[4'h5], _RANDOM[4'h6][9:0]};
        r_1_rvcMask_0 = _RANDOM[4'h6][10];
        r_1_rvcMask_1 = _RANDOM[4'h6][11];
        r_1_rvcMask_2 = _RANDOM[4'h6][12];
        r_1_rvcMask_3 = _RANDOM[4'h6][13];
        r_1_rvcMask_4 = _RANDOM[4'h6][14];
        r_1_rvcMask_5 = _RANDOM[4'h6][15];
        r_1_rvcMask_6 = _RANDOM[4'h6][16];
        r_1_rvcMask_7 = _RANDOM[4'h6][17];
        r_1_rvcMask_8 = _RANDOM[4'h6][18];
        r_1_rvcMask_9 = _RANDOM[4'h6][19];
        r_1_rvcMask_10 = _RANDOM[4'h6][20];
        r_1_rvcMask_11 = _RANDOM[4'h6][21];
        r_1_rvcMask_12 = _RANDOM[4'h6][22];
        r_1_rvcMask_13 = _RANDOM[4'h6][23];
        r_1_rvcMask_14 = _RANDOM[4'h6][24];
        r_1_rvcMask_15 = _RANDOM[4'h6][25];
        raddr_dup_0_2 = _RANDOM[4'h6][31:26];
        raddr_dup_1_2 = _RANDOM[4'h7][5:0];
        wen_dup_last_REG_2 = _RANDOM[4'h7][6];
        waddr_dup_0_2 = _RANDOM[4'h7][12:7];
        r_2_brMask_0 = _RANDOM[4'h7][13];
        r_2_brMask_1 = _RANDOM[4'h7][14];
        r_2_brMask_2 = _RANDOM[4'h7][15];
        r_2_brMask_3 = _RANDOM[4'h7][16];
        r_2_brMask_4 = _RANDOM[4'h7][17];
        r_2_brMask_5 = _RANDOM[4'h7][18];
        r_2_brMask_6 = _RANDOM[4'h7][19];
        r_2_brMask_7 = _RANDOM[4'h7][20];
        r_2_brMask_8 = _RANDOM[4'h7][21];
        r_2_brMask_9 = _RANDOM[4'h7][22];
        r_2_brMask_10 = _RANDOM[4'h7][23];
        r_2_brMask_11 = _RANDOM[4'h7][24];
        r_2_brMask_12 = _RANDOM[4'h7][25];
        r_2_brMask_13 = _RANDOM[4'h7][26];
        r_2_brMask_14 = _RANDOM[4'h7][27];
        r_2_brMask_15 = _RANDOM[4'h7][28];
        r_2_jmpInfo_valid = _RANDOM[4'h7][29];
        r_2_jmpInfo_bits_0 = _RANDOM[4'h7][30];
        r_2_jmpInfo_bits_1 = _RANDOM[4'h7][31];
        r_2_jmpInfo_bits_2 = _RANDOM[4'h8][0];
        r_2_jmpOffset = _RANDOM[4'h8][4:1];
        r_2_jalTarget = {_RANDOM[4'h8][31:5], _RANDOM[4'h9][22:0]};
        r_2_rvcMask_0 = _RANDOM[4'h9][23];
        r_2_rvcMask_1 = _RANDOM[4'h9][24];
        r_2_rvcMask_2 = _RANDOM[4'h9][25];
        r_2_rvcMask_3 = _RANDOM[4'h9][26];
        r_2_rvcMask_4 = _RANDOM[4'h9][27];
        r_2_rvcMask_5 = _RANDOM[4'h9][28];
        r_2_rvcMask_6 = _RANDOM[4'h9][29];
        r_2_rvcMask_7 = _RANDOM[4'h9][30];
        r_2_rvcMask_8 = _RANDOM[4'h9][31];
        r_2_rvcMask_9 = _RANDOM[4'hA][0];
        r_2_rvcMask_10 = _RANDOM[4'hA][1];
        r_2_rvcMask_11 = _RANDOM[4'hA][2];
        r_2_rvcMask_12 = _RANDOM[4'hA][3];
        r_2_rvcMask_13 = _RANDOM[4'hA][4];
        r_2_rvcMask_14 = _RANDOM[4'hA][5];
        r_2_rvcMask_15 = _RANDOM[4'hA][6];
        raddr_dup_0_3 = _RANDOM[4'hA][12:7];
        raddr_dup_1_3 = _RANDOM[4'hA][18:13];
        wen_dup_last_REG_3 = _RANDOM[4'hA][19];
        waddr_dup_0_3 = _RANDOM[4'hA][25:20];
        r_3_brMask_0 = _RANDOM[4'hA][26];
        r_3_brMask_1 = _RANDOM[4'hA][27];
        r_3_brMask_2 = _RANDOM[4'hA][28];
        r_3_brMask_3 = _RANDOM[4'hA][29];
        r_3_brMask_4 = _RANDOM[4'hA][30];
        r_3_brMask_5 = _RANDOM[4'hA][31];
        r_3_brMask_6 = _RANDOM[4'hB][0];
        r_3_brMask_7 = _RANDOM[4'hB][1];
        r_3_brMask_8 = _RANDOM[4'hB][2];
        r_3_brMask_9 = _RANDOM[4'hB][3];
        r_3_brMask_10 = _RANDOM[4'hB][4];
        r_3_brMask_11 = _RANDOM[4'hB][5];
        r_3_brMask_12 = _RANDOM[4'hB][6];
        r_3_brMask_13 = _RANDOM[4'hB][7];
        r_3_brMask_14 = _RANDOM[4'hB][8];
        r_3_brMask_15 = _RANDOM[4'hB][9];
        r_3_jmpInfo_valid = _RANDOM[4'hB][10];
        r_3_jmpInfo_bits_0 = _RANDOM[4'hB][11];
        r_3_jmpInfo_bits_1 = _RANDOM[4'hB][12];
        r_3_jmpInfo_bits_2 = _RANDOM[4'hB][13];
        r_3_jmpOffset = _RANDOM[4'hB][17:14];
        r_3_jalTarget = {_RANDOM[4'hB][31:18], _RANDOM[4'hC], _RANDOM[4'hD][3:0]};
        r_3_rvcMask_0 = _RANDOM[4'hD][4];
        r_3_rvcMask_1 = _RANDOM[4'hD][5];
        r_3_rvcMask_2 = _RANDOM[4'hD][6];
        r_3_rvcMask_3 = _RANDOM[4'hD][7];
        r_3_rvcMask_4 = _RANDOM[4'hD][8];
        r_3_rvcMask_5 = _RANDOM[4'hD][9];
        r_3_rvcMask_6 = _RANDOM[4'hD][10];
        r_3_rvcMask_7 = _RANDOM[4'hD][11];
        r_3_rvcMask_8 = _RANDOM[4'hD][12];
        r_3_rvcMask_9 = _RANDOM[4'hD][13];
        r_3_rvcMask_10 = _RANDOM[4'hD][14];
        r_3_rvcMask_11 = _RANDOM[4'hD][15];
        r_3_rvcMask_12 = _RANDOM[4'hD][16];
        r_3_rvcMask_13 = _RANDOM[4'hD][17];
        r_3_rvcMask_14 = _RANDOM[4'hD][18];
        r_3_rvcMask_15 = _RANDOM[4'hD][19];
        raddr_dup = _RANDOM[4'hD][25:20];
        raddr_dup_2 = _RANDOM[4'hD][31:26];
      `endif // RANDOMIZE_REG_INIT
      if (reset) begin
        wen_dup_last_REG = 1'h0;
        wen_dup_last_REG_1 = 1'h0;
        wen_dup_last_REG_2 = 1'h0;
        wen_dup_last_REG_3 = 1'h0;
      end
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  DataModule__16entry_8 dataBanks_0 (
    .clock                     (clock),
    .io_raddr_0                (raddr_dup_0[3:0]),
    .io_raddr_1                (raddr_dup_1[3:0]),
    .io_rdata_0_brMask_0       (_dataBanks_0_io_rdata_0_brMask_0),
    .io_rdata_0_brMask_1       (_dataBanks_0_io_rdata_0_brMask_1),
    .io_rdata_0_brMask_2       (_dataBanks_0_io_rdata_0_brMask_2),
    .io_rdata_0_brMask_3       (_dataBanks_0_io_rdata_0_brMask_3),
    .io_rdata_0_brMask_4       (_dataBanks_0_io_rdata_0_brMask_4),
    .io_rdata_0_brMask_5       (_dataBanks_0_io_rdata_0_brMask_5),
    .io_rdata_0_brMask_6       (_dataBanks_0_io_rdata_0_brMask_6),
    .io_rdata_0_brMask_7       (_dataBanks_0_io_rdata_0_brMask_7),
    .io_rdata_0_brMask_8       (_dataBanks_0_io_rdata_0_brMask_8),
    .io_rdata_0_brMask_9       (_dataBanks_0_io_rdata_0_brMask_9),
    .io_rdata_0_brMask_10      (_dataBanks_0_io_rdata_0_brMask_10),
    .io_rdata_0_brMask_11      (_dataBanks_0_io_rdata_0_brMask_11),
    .io_rdata_0_brMask_12      (_dataBanks_0_io_rdata_0_brMask_12),
    .io_rdata_0_brMask_13      (_dataBanks_0_io_rdata_0_brMask_13),
    .io_rdata_0_brMask_14      (_dataBanks_0_io_rdata_0_brMask_14),
    .io_rdata_0_brMask_15      (_dataBanks_0_io_rdata_0_brMask_15),
    .io_rdata_0_jmpInfo_valid  (_dataBanks_0_io_rdata_0_jmpInfo_valid),
    .io_rdata_0_jmpInfo_bits_0 (_dataBanks_0_io_rdata_0_jmpInfo_bits_0),
    .io_rdata_0_jmpInfo_bits_1 (_dataBanks_0_io_rdata_0_jmpInfo_bits_1),
    .io_rdata_0_jmpInfo_bits_2 (_dataBanks_0_io_rdata_0_jmpInfo_bits_2),
    .io_rdata_0_jmpOffset      (_dataBanks_0_io_rdata_0_jmpOffset),
    .io_rdata_0_rvcMask_0      (_dataBanks_0_io_rdata_0_rvcMask_0),
    .io_rdata_0_rvcMask_1      (_dataBanks_0_io_rdata_0_rvcMask_1),
    .io_rdata_0_rvcMask_2      (_dataBanks_0_io_rdata_0_rvcMask_2),
    .io_rdata_0_rvcMask_3      (_dataBanks_0_io_rdata_0_rvcMask_3),
    .io_rdata_0_rvcMask_4      (_dataBanks_0_io_rdata_0_rvcMask_4),
    .io_rdata_0_rvcMask_5      (_dataBanks_0_io_rdata_0_rvcMask_5),
    .io_rdata_0_rvcMask_6      (_dataBanks_0_io_rdata_0_rvcMask_6),
    .io_rdata_0_rvcMask_7      (_dataBanks_0_io_rdata_0_rvcMask_7),
    .io_rdata_0_rvcMask_8      (_dataBanks_0_io_rdata_0_rvcMask_8),
    .io_rdata_0_rvcMask_9      (_dataBanks_0_io_rdata_0_rvcMask_9),
    .io_rdata_0_rvcMask_10     (_dataBanks_0_io_rdata_0_rvcMask_10),
    .io_rdata_0_rvcMask_11     (_dataBanks_0_io_rdata_0_rvcMask_11),
    .io_rdata_0_rvcMask_12     (_dataBanks_0_io_rdata_0_rvcMask_12),
    .io_rdata_0_rvcMask_13     (_dataBanks_0_io_rdata_0_rvcMask_13),
    .io_rdata_0_rvcMask_14     (_dataBanks_0_io_rdata_0_rvcMask_14),
    .io_rdata_0_rvcMask_15     (_dataBanks_0_io_rdata_0_rvcMask_15),
    .io_rdata_1_brMask_0       (_dataBanks_0_io_rdata_1_brMask_0),
    .io_rdata_1_brMask_1       (_dataBanks_0_io_rdata_1_brMask_1),
    .io_rdata_1_brMask_2       (_dataBanks_0_io_rdata_1_brMask_2),
    .io_rdata_1_brMask_3       (_dataBanks_0_io_rdata_1_brMask_3),
    .io_rdata_1_brMask_4       (_dataBanks_0_io_rdata_1_brMask_4),
    .io_rdata_1_brMask_5       (_dataBanks_0_io_rdata_1_brMask_5),
    .io_rdata_1_brMask_6       (_dataBanks_0_io_rdata_1_brMask_6),
    .io_rdata_1_brMask_7       (_dataBanks_0_io_rdata_1_brMask_7),
    .io_rdata_1_brMask_8       (_dataBanks_0_io_rdata_1_brMask_8),
    .io_rdata_1_brMask_9       (_dataBanks_0_io_rdata_1_brMask_9),
    .io_rdata_1_brMask_10      (_dataBanks_0_io_rdata_1_brMask_10),
    .io_rdata_1_brMask_11      (_dataBanks_0_io_rdata_1_brMask_11),
    .io_rdata_1_brMask_12      (_dataBanks_0_io_rdata_1_brMask_12),
    .io_rdata_1_brMask_13      (_dataBanks_0_io_rdata_1_brMask_13),
    .io_rdata_1_brMask_14      (_dataBanks_0_io_rdata_1_brMask_14),
    .io_rdata_1_brMask_15      (_dataBanks_0_io_rdata_1_brMask_15),
    .io_rdata_1_jmpInfo_valid  (_dataBanks_0_io_rdata_1_jmpInfo_valid),
    .io_rdata_1_jmpInfo_bits_0 (_dataBanks_0_io_rdata_1_jmpInfo_bits_0),
    .io_rdata_1_jmpInfo_bits_1 (_dataBanks_0_io_rdata_1_jmpInfo_bits_1),
    .io_rdata_1_jmpInfo_bits_2 (_dataBanks_0_io_rdata_1_jmpInfo_bits_2),
    .io_rdata_1_jmpOffset      (_dataBanks_0_io_rdata_1_jmpOffset),
    .io_rdata_1_jalTarget      (_dataBanks_0_io_rdata_1_jalTarget),
    .io_rdata_1_rvcMask_0      (_dataBanks_0_io_rdata_1_rvcMask_0),
    .io_rdata_1_rvcMask_1      (_dataBanks_0_io_rdata_1_rvcMask_1),
    .io_rdata_1_rvcMask_2      (_dataBanks_0_io_rdata_1_rvcMask_2),
    .io_rdata_1_rvcMask_3      (_dataBanks_0_io_rdata_1_rvcMask_3),
    .io_rdata_1_rvcMask_4      (_dataBanks_0_io_rdata_1_rvcMask_4),
    .io_rdata_1_rvcMask_5      (_dataBanks_0_io_rdata_1_rvcMask_5),
    .io_rdata_1_rvcMask_6      (_dataBanks_0_io_rdata_1_rvcMask_6),
    .io_rdata_1_rvcMask_7      (_dataBanks_0_io_rdata_1_rvcMask_7),
    .io_rdata_1_rvcMask_8      (_dataBanks_0_io_rdata_1_rvcMask_8),
    .io_rdata_1_rvcMask_9      (_dataBanks_0_io_rdata_1_rvcMask_9),
    .io_rdata_1_rvcMask_10     (_dataBanks_0_io_rdata_1_rvcMask_10),
    .io_rdata_1_rvcMask_11     (_dataBanks_0_io_rdata_1_rvcMask_11),
    .io_rdata_1_rvcMask_12     (_dataBanks_0_io_rdata_1_rvcMask_12),
    .io_rdata_1_rvcMask_13     (_dataBanks_0_io_rdata_1_rvcMask_13),
    .io_rdata_1_rvcMask_14     (_dataBanks_0_io_rdata_1_rvcMask_14),
    .io_rdata_1_rvcMask_15     (_dataBanks_0_io_rdata_1_rvcMask_15),
    .io_wen_0                  (wen_dup_last_REG & waddr_dup_0[5:4] == 2'h0),
    .io_waddr_0                (waddr_dup_0[3:0]),
    .io_wdata_0_brMask_0       (r_brMask_0),
    .io_wdata_0_brMask_1       (r_brMask_1),
    .io_wdata_0_brMask_2       (r_brMask_2),
    .io_wdata_0_brMask_3       (r_brMask_3),
    .io_wdata_0_brMask_4       (r_brMask_4),
    .io_wdata_0_brMask_5       (r_brMask_5),
    .io_wdata_0_brMask_6       (r_brMask_6),
    .io_wdata_0_brMask_7       (r_brMask_7),
    .io_wdata_0_brMask_8       (r_brMask_8),
    .io_wdata_0_brMask_9       (r_brMask_9),
    .io_wdata_0_brMask_10      (r_brMask_10),
    .io_wdata_0_brMask_11      (r_brMask_11),
    .io_wdata_0_brMask_12      (r_brMask_12),
    .io_wdata_0_brMask_13      (r_brMask_13),
    .io_wdata_0_brMask_14      (r_brMask_14),
    .io_wdata_0_brMask_15      (r_brMask_15),
    .io_wdata_0_jmpInfo_valid  (r_jmpInfo_valid),
    .io_wdata_0_jmpInfo_bits_0 (r_jmpInfo_bits_0),
    .io_wdata_0_jmpInfo_bits_1 (r_jmpInfo_bits_1),
    .io_wdata_0_jmpInfo_bits_2 (r_jmpInfo_bits_2),
    .io_wdata_0_jmpOffset      (r_jmpOffset),
    .io_wdata_0_jalTarget      (r_jalTarget),
    .io_wdata_0_rvcMask_0      (r_rvcMask_0),
    .io_wdata_0_rvcMask_1      (r_rvcMask_1),
    .io_wdata_0_rvcMask_2      (r_rvcMask_2),
    .io_wdata_0_rvcMask_3      (r_rvcMask_3),
    .io_wdata_0_rvcMask_4      (r_rvcMask_4),
    .io_wdata_0_rvcMask_5      (r_rvcMask_5),
    .io_wdata_0_rvcMask_6      (r_rvcMask_6),
    .io_wdata_0_rvcMask_7      (r_rvcMask_7),
    .io_wdata_0_rvcMask_8      (r_rvcMask_8),
    .io_wdata_0_rvcMask_9      (r_rvcMask_9),
    .io_wdata_0_rvcMask_10     (r_rvcMask_10),
    .io_wdata_0_rvcMask_11     (r_rvcMask_11),
    .io_wdata_0_rvcMask_12     (r_rvcMask_12),
    .io_wdata_0_rvcMask_13     (r_rvcMask_13),
    .io_wdata_0_rvcMask_14     (r_rvcMask_14),
    .io_wdata_0_rvcMask_15     (r_rvcMask_15)
  );
  DataModule__16entry_8 dataBanks_1 (
    .clock                     (clock),
    .io_raddr_0                (raddr_dup_0_1[3:0]),
    .io_raddr_1                (raddr_dup_1_1[3:0]),
    .io_rdata_0_brMask_0       (_dataBanks_1_io_rdata_0_brMask_0),
    .io_rdata_0_brMask_1       (_dataBanks_1_io_rdata_0_brMask_1),
    .io_rdata_0_brMask_2       (_dataBanks_1_io_rdata_0_brMask_2),
    .io_rdata_0_brMask_3       (_dataBanks_1_io_rdata_0_brMask_3),
    .io_rdata_0_brMask_4       (_dataBanks_1_io_rdata_0_brMask_4),
    .io_rdata_0_brMask_5       (_dataBanks_1_io_rdata_0_brMask_5),
    .io_rdata_0_brMask_6       (_dataBanks_1_io_rdata_0_brMask_6),
    .io_rdata_0_brMask_7       (_dataBanks_1_io_rdata_0_brMask_7),
    .io_rdata_0_brMask_8       (_dataBanks_1_io_rdata_0_brMask_8),
    .io_rdata_0_brMask_9       (_dataBanks_1_io_rdata_0_brMask_9),
    .io_rdata_0_brMask_10      (_dataBanks_1_io_rdata_0_brMask_10),
    .io_rdata_0_brMask_11      (_dataBanks_1_io_rdata_0_brMask_11),
    .io_rdata_0_brMask_12      (_dataBanks_1_io_rdata_0_brMask_12),
    .io_rdata_0_brMask_13      (_dataBanks_1_io_rdata_0_brMask_13),
    .io_rdata_0_brMask_14      (_dataBanks_1_io_rdata_0_brMask_14),
    .io_rdata_0_brMask_15      (_dataBanks_1_io_rdata_0_brMask_15),
    .io_rdata_0_jmpInfo_valid  (_dataBanks_1_io_rdata_0_jmpInfo_valid),
    .io_rdata_0_jmpInfo_bits_0 (_dataBanks_1_io_rdata_0_jmpInfo_bits_0),
    .io_rdata_0_jmpInfo_bits_1 (_dataBanks_1_io_rdata_0_jmpInfo_bits_1),
    .io_rdata_0_jmpInfo_bits_2 (_dataBanks_1_io_rdata_0_jmpInfo_bits_2),
    .io_rdata_0_jmpOffset      (_dataBanks_1_io_rdata_0_jmpOffset),
    .io_rdata_0_rvcMask_0      (_dataBanks_1_io_rdata_0_rvcMask_0),
    .io_rdata_0_rvcMask_1      (_dataBanks_1_io_rdata_0_rvcMask_1),
    .io_rdata_0_rvcMask_2      (_dataBanks_1_io_rdata_0_rvcMask_2),
    .io_rdata_0_rvcMask_3      (_dataBanks_1_io_rdata_0_rvcMask_3),
    .io_rdata_0_rvcMask_4      (_dataBanks_1_io_rdata_0_rvcMask_4),
    .io_rdata_0_rvcMask_5      (_dataBanks_1_io_rdata_0_rvcMask_5),
    .io_rdata_0_rvcMask_6      (_dataBanks_1_io_rdata_0_rvcMask_6),
    .io_rdata_0_rvcMask_7      (_dataBanks_1_io_rdata_0_rvcMask_7),
    .io_rdata_0_rvcMask_8      (_dataBanks_1_io_rdata_0_rvcMask_8),
    .io_rdata_0_rvcMask_9      (_dataBanks_1_io_rdata_0_rvcMask_9),
    .io_rdata_0_rvcMask_10     (_dataBanks_1_io_rdata_0_rvcMask_10),
    .io_rdata_0_rvcMask_11     (_dataBanks_1_io_rdata_0_rvcMask_11),
    .io_rdata_0_rvcMask_12     (_dataBanks_1_io_rdata_0_rvcMask_12),
    .io_rdata_0_rvcMask_13     (_dataBanks_1_io_rdata_0_rvcMask_13),
    .io_rdata_0_rvcMask_14     (_dataBanks_1_io_rdata_0_rvcMask_14),
    .io_rdata_0_rvcMask_15     (_dataBanks_1_io_rdata_0_rvcMask_15),
    .io_rdata_1_brMask_0       (_dataBanks_1_io_rdata_1_brMask_0),
    .io_rdata_1_brMask_1       (_dataBanks_1_io_rdata_1_brMask_1),
    .io_rdata_1_brMask_2       (_dataBanks_1_io_rdata_1_brMask_2),
    .io_rdata_1_brMask_3       (_dataBanks_1_io_rdata_1_brMask_3),
    .io_rdata_1_brMask_4       (_dataBanks_1_io_rdata_1_brMask_4),
    .io_rdata_1_brMask_5       (_dataBanks_1_io_rdata_1_brMask_5),
    .io_rdata_1_brMask_6       (_dataBanks_1_io_rdata_1_brMask_6),
    .io_rdata_1_brMask_7       (_dataBanks_1_io_rdata_1_brMask_7),
    .io_rdata_1_brMask_8       (_dataBanks_1_io_rdata_1_brMask_8),
    .io_rdata_1_brMask_9       (_dataBanks_1_io_rdata_1_brMask_9),
    .io_rdata_1_brMask_10      (_dataBanks_1_io_rdata_1_brMask_10),
    .io_rdata_1_brMask_11      (_dataBanks_1_io_rdata_1_brMask_11),
    .io_rdata_1_brMask_12      (_dataBanks_1_io_rdata_1_brMask_12),
    .io_rdata_1_brMask_13      (_dataBanks_1_io_rdata_1_brMask_13),
    .io_rdata_1_brMask_14      (_dataBanks_1_io_rdata_1_brMask_14),
    .io_rdata_1_brMask_15      (_dataBanks_1_io_rdata_1_brMask_15),
    .io_rdata_1_jmpInfo_valid  (_dataBanks_1_io_rdata_1_jmpInfo_valid),
    .io_rdata_1_jmpInfo_bits_0 (_dataBanks_1_io_rdata_1_jmpInfo_bits_0),
    .io_rdata_1_jmpInfo_bits_1 (_dataBanks_1_io_rdata_1_jmpInfo_bits_1),
    .io_rdata_1_jmpInfo_bits_2 (_dataBanks_1_io_rdata_1_jmpInfo_bits_2),
    .io_rdata_1_jmpOffset      (_dataBanks_1_io_rdata_1_jmpOffset),
    .io_rdata_1_jalTarget      (_dataBanks_1_io_rdata_1_jalTarget),
    .io_rdata_1_rvcMask_0      (_dataBanks_1_io_rdata_1_rvcMask_0),
    .io_rdata_1_rvcMask_1      (_dataBanks_1_io_rdata_1_rvcMask_1),
    .io_rdata_1_rvcMask_2      (_dataBanks_1_io_rdata_1_rvcMask_2),
    .io_rdata_1_rvcMask_3      (_dataBanks_1_io_rdata_1_rvcMask_3),
    .io_rdata_1_rvcMask_4      (_dataBanks_1_io_rdata_1_rvcMask_4),
    .io_rdata_1_rvcMask_5      (_dataBanks_1_io_rdata_1_rvcMask_5),
    .io_rdata_1_rvcMask_6      (_dataBanks_1_io_rdata_1_rvcMask_6),
    .io_rdata_1_rvcMask_7      (_dataBanks_1_io_rdata_1_rvcMask_7),
    .io_rdata_1_rvcMask_8      (_dataBanks_1_io_rdata_1_rvcMask_8),
    .io_rdata_1_rvcMask_9      (_dataBanks_1_io_rdata_1_rvcMask_9),
    .io_rdata_1_rvcMask_10     (_dataBanks_1_io_rdata_1_rvcMask_10),
    .io_rdata_1_rvcMask_11     (_dataBanks_1_io_rdata_1_rvcMask_11),
    .io_rdata_1_rvcMask_12     (_dataBanks_1_io_rdata_1_rvcMask_12),
    .io_rdata_1_rvcMask_13     (_dataBanks_1_io_rdata_1_rvcMask_13),
    .io_rdata_1_rvcMask_14     (_dataBanks_1_io_rdata_1_rvcMask_14),
    .io_rdata_1_rvcMask_15     (_dataBanks_1_io_rdata_1_rvcMask_15),
    .io_wen_0                  (wen_dup_last_REG_1 & waddr_dup_0_1[5:4] == 2'h1),
    .io_waddr_0                (waddr_dup_0_1[3:0]),
    .io_wdata_0_brMask_0       (r_1_brMask_0),
    .io_wdata_0_brMask_1       (r_1_brMask_1),
    .io_wdata_0_brMask_2       (r_1_brMask_2),
    .io_wdata_0_brMask_3       (r_1_brMask_3),
    .io_wdata_0_brMask_4       (r_1_brMask_4),
    .io_wdata_0_brMask_5       (r_1_brMask_5),
    .io_wdata_0_brMask_6       (r_1_brMask_6),
    .io_wdata_0_brMask_7       (r_1_brMask_7),
    .io_wdata_0_brMask_8       (r_1_brMask_8),
    .io_wdata_0_brMask_9       (r_1_brMask_9),
    .io_wdata_0_brMask_10      (r_1_brMask_10),
    .io_wdata_0_brMask_11      (r_1_brMask_11),
    .io_wdata_0_brMask_12      (r_1_brMask_12),
    .io_wdata_0_brMask_13      (r_1_brMask_13),
    .io_wdata_0_brMask_14      (r_1_brMask_14),
    .io_wdata_0_brMask_15      (r_1_brMask_15),
    .io_wdata_0_jmpInfo_valid  (r_1_jmpInfo_valid),
    .io_wdata_0_jmpInfo_bits_0 (r_1_jmpInfo_bits_0),
    .io_wdata_0_jmpInfo_bits_1 (r_1_jmpInfo_bits_1),
    .io_wdata_0_jmpInfo_bits_2 (r_1_jmpInfo_bits_2),
    .io_wdata_0_jmpOffset      (r_1_jmpOffset),
    .io_wdata_0_jalTarget      (r_1_jalTarget),
    .io_wdata_0_rvcMask_0      (r_1_rvcMask_0),
    .io_wdata_0_rvcMask_1      (r_1_rvcMask_1),
    .io_wdata_0_rvcMask_2      (r_1_rvcMask_2),
    .io_wdata_0_rvcMask_3      (r_1_rvcMask_3),
    .io_wdata_0_rvcMask_4      (r_1_rvcMask_4),
    .io_wdata_0_rvcMask_5      (r_1_rvcMask_5),
    .io_wdata_0_rvcMask_6      (r_1_rvcMask_6),
    .io_wdata_0_rvcMask_7      (r_1_rvcMask_7),
    .io_wdata_0_rvcMask_8      (r_1_rvcMask_8),
    .io_wdata_0_rvcMask_9      (r_1_rvcMask_9),
    .io_wdata_0_rvcMask_10     (r_1_rvcMask_10),
    .io_wdata_0_rvcMask_11     (r_1_rvcMask_11),
    .io_wdata_0_rvcMask_12     (r_1_rvcMask_12),
    .io_wdata_0_rvcMask_13     (r_1_rvcMask_13),
    .io_wdata_0_rvcMask_14     (r_1_rvcMask_14),
    .io_wdata_0_rvcMask_15     (r_1_rvcMask_15)
  );
  DataModule__16entry_8 dataBanks_2 (
    .clock                     (clock),
    .io_raddr_0                (raddr_dup_0_2[3:0]),
    .io_raddr_1                (raddr_dup_1_2[3:0]),
    .io_rdata_0_brMask_0       (_dataBanks_2_io_rdata_0_brMask_0),
    .io_rdata_0_brMask_1       (_dataBanks_2_io_rdata_0_brMask_1),
    .io_rdata_0_brMask_2       (_dataBanks_2_io_rdata_0_brMask_2),
    .io_rdata_0_brMask_3       (_dataBanks_2_io_rdata_0_brMask_3),
    .io_rdata_0_brMask_4       (_dataBanks_2_io_rdata_0_brMask_4),
    .io_rdata_0_brMask_5       (_dataBanks_2_io_rdata_0_brMask_5),
    .io_rdata_0_brMask_6       (_dataBanks_2_io_rdata_0_brMask_6),
    .io_rdata_0_brMask_7       (_dataBanks_2_io_rdata_0_brMask_7),
    .io_rdata_0_brMask_8       (_dataBanks_2_io_rdata_0_brMask_8),
    .io_rdata_0_brMask_9       (_dataBanks_2_io_rdata_0_brMask_9),
    .io_rdata_0_brMask_10      (_dataBanks_2_io_rdata_0_brMask_10),
    .io_rdata_0_brMask_11      (_dataBanks_2_io_rdata_0_brMask_11),
    .io_rdata_0_brMask_12      (_dataBanks_2_io_rdata_0_brMask_12),
    .io_rdata_0_brMask_13      (_dataBanks_2_io_rdata_0_brMask_13),
    .io_rdata_0_brMask_14      (_dataBanks_2_io_rdata_0_brMask_14),
    .io_rdata_0_brMask_15      (_dataBanks_2_io_rdata_0_brMask_15),
    .io_rdata_0_jmpInfo_valid  (_dataBanks_2_io_rdata_0_jmpInfo_valid),
    .io_rdata_0_jmpInfo_bits_0 (_dataBanks_2_io_rdata_0_jmpInfo_bits_0),
    .io_rdata_0_jmpInfo_bits_1 (_dataBanks_2_io_rdata_0_jmpInfo_bits_1),
    .io_rdata_0_jmpInfo_bits_2 (_dataBanks_2_io_rdata_0_jmpInfo_bits_2),
    .io_rdata_0_jmpOffset      (_dataBanks_2_io_rdata_0_jmpOffset),
    .io_rdata_0_rvcMask_0      (_dataBanks_2_io_rdata_0_rvcMask_0),
    .io_rdata_0_rvcMask_1      (_dataBanks_2_io_rdata_0_rvcMask_1),
    .io_rdata_0_rvcMask_2      (_dataBanks_2_io_rdata_0_rvcMask_2),
    .io_rdata_0_rvcMask_3      (_dataBanks_2_io_rdata_0_rvcMask_3),
    .io_rdata_0_rvcMask_4      (_dataBanks_2_io_rdata_0_rvcMask_4),
    .io_rdata_0_rvcMask_5      (_dataBanks_2_io_rdata_0_rvcMask_5),
    .io_rdata_0_rvcMask_6      (_dataBanks_2_io_rdata_0_rvcMask_6),
    .io_rdata_0_rvcMask_7      (_dataBanks_2_io_rdata_0_rvcMask_7),
    .io_rdata_0_rvcMask_8      (_dataBanks_2_io_rdata_0_rvcMask_8),
    .io_rdata_0_rvcMask_9      (_dataBanks_2_io_rdata_0_rvcMask_9),
    .io_rdata_0_rvcMask_10     (_dataBanks_2_io_rdata_0_rvcMask_10),
    .io_rdata_0_rvcMask_11     (_dataBanks_2_io_rdata_0_rvcMask_11),
    .io_rdata_0_rvcMask_12     (_dataBanks_2_io_rdata_0_rvcMask_12),
    .io_rdata_0_rvcMask_13     (_dataBanks_2_io_rdata_0_rvcMask_13),
    .io_rdata_0_rvcMask_14     (_dataBanks_2_io_rdata_0_rvcMask_14),
    .io_rdata_0_rvcMask_15     (_dataBanks_2_io_rdata_0_rvcMask_15),
    .io_rdata_1_brMask_0       (_dataBanks_2_io_rdata_1_brMask_0),
    .io_rdata_1_brMask_1       (_dataBanks_2_io_rdata_1_brMask_1),
    .io_rdata_1_brMask_2       (_dataBanks_2_io_rdata_1_brMask_2),
    .io_rdata_1_brMask_3       (_dataBanks_2_io_rdata_1_brMask_3),
    .io_rdata_1_brMask_4       (_dataBanks_2_io_rdata_1_brMask_4),
    .io_rdata_1_brMask_5       (_dataBanks_2_io_rdata_1_brMask_5),
    .io_rdata_1_brMask_6       (_dataBanks_2_io_rdata_1_brMask_6),
    .io_rdata_1_brMask_7       (_dataBanks_2_io_rdata_1_brMask_7),
    .io_rdata_1_brMask_8       (_dataBanks_2_io_rdata_1_brMask_8),
    .io_rdata_1_brMask_9       (_dataBanks_2_io_rdata_1_brMask_9),
    .io_rdata_1_brMask_10      (_dataBanks_2_io_rdata_1_brMask_10),
    .io_rdata_1_brMask_11      (_dataBanks_2_io_rdata_1_brMask_11),
    .io_rdata_1_brMask_12      (_dataBanks_2_io_rdata_1_brMask_12),
    .io_rdata_1_brMask_13      (_dataBanks_2_io_rdata_1_brMask_13),
    .io_rdata_1_brMask_14      (_dataBanks_2_io_rdata_1_brMask_14),
    .io_rdata_1_brMask_15      (_dataBanks_2_io_rdata_1_brMask_15),
    .io_rdata_1_jmpInfo_valid  (_dataBanks_2_io_rdata_1_jmpInfo_valid),
    .io_rdata_1_jmpInfo_bits_0 (_dataBanks_2_io_rdata_1_jmpInfo_bits_0),
    .io_rdata_1_jmpInfo_bits_1 (_dataBanks_2_io_rdata_1_jmpInfo_bits_1),
    .io_rdata_1_jmpInfo_bits_2 (_dataBanks_2_io_rdata_1_jmpInfo_bits_2),
    .io_rdata_1_jmpOffset      (_dataBanks_2_io_rdata_1_jmpOffset),
    .io_rdata_1_jalTarget      (_dataBanks_2_io_rdata_1_jalTarget),
    .io_rdata_1_rvcMask_0      (_dataBanks_2_io_rdata_1_rvcMask_0),
    .io_rdata_1_rvcMask_1      (_dataBanks_2_io_rdata_1_rvcMask_1),
    .io_rdata_1_rvcMask_2      (_dataBanks_2_io_rdata_1_rvcMask_2),
    .io_rdata_1_rvcMask_3      (_dataBanks_2_io_rdata_1_rvcMask_3),
    .io_rdata_1_rvcMask_4      (_dataBanks_2_io_rdata_1_rvcMask_4),
    .io_rdata_1_rvcMask_5      (_dataBanks_2_io_rdata_1_rvcMask_5),
    .io_rdata_1_rvcMask_6      (_dataBanks_2_io_rdata_1_rvcMask_6),
    .io_rdata_1_rvcMask_7      (_dataBanks_2_io_rdata_1_rvcMask_7),
    .io_rdata_1_rvcMask_8      (_dataBanks_2_io_rdata_1_rvcMask_8),
    .io_rdata_1_rvcMask_9      (_dataBanks_2_io_rdata_1_rvcMask_9),
    .io_rdata_1_rvcMask_10     (_dataBanks_2_io_rdata_1_rvcMask_10),
    .io_rdata_1_rvcMask_11     (_dataBanks_2_io_rdata_1_rvcMask_11),
    .io_rdata_1_rvcMask_12     (_dataBanks_2_io_rdata_1_rvcMask_12),
    .io_rdata_1_rvcMask_13     (_dataBanks_2_io_rdata_1_rvcMask_13),
    .io_rdata_1_rvcMask_14     (_dataBanks_2_io_rdata_1_rvcMask_14),
    .io_rdata_1_rvcMask_15     (_dataBanks_2_io_rdata_1_rvcMask_15),
    .io_wen_0                  (wen_dup_last_REG_2 & waddr_dup_0_2[5:4] == 2'h2),
    .io_waddr_0                (waddr_dup_0_2[3:0]),
    .io_wdata_0_brMask_0       (r_2_brMask_0),
    .io_wdata_0_brMask_1       (r_2_brMask_1),
    .io_wdata_0_brMask_2       (r_2_brMask_2),
    .io_wdata_0_brMask_3       (r_2_brMask_3),
    .io_wdata_0_brMask_4       (r_2_brMask_4),
    .io_wdata_0_brMask_5       (r_2_brMask_5),
    .io_wdata_0_brMask_6       (r_2_brMask_6),
    .io_wdata_0_brMask_7       (r_2_brMask_7),
    .io_wdata_0_brMask_8       (r_2_brMask_8),
    .io_wdata_0_brMask_9       (r_2_brMask_9),
    .io_wdata_0_brMask_10      (r_2_brMask_10),
    .io_wdata_0_brMask_11      (r_2_brMask_11),
    .io_wdata_0_brMask_12      (r_2_brMask_12),
    .io_wdata_0_brMask_13      (r_2_brMask_13),
    .io_wdata_0_brMask_14      (r_2_brMask_14),
    .io_wdata_0_brMask_15      (r_2_brMask_15),
    .io_wdata_0_jmpInfo_valid  (r_2_jmpInfo_valid),
    .io_wdata_0_jmpInfo_bits_0 (r_2_jmpInfo_bits_0),
    .io_wdata_0_jmpInfo_bits_1 (r_2_jmpInfo_bits_1),
    .io_wdata_0_jmpInfo_bits_2 (r_2_jmpInfo_bits_2),
    .io_wdata_0_jmpOffset      (r_2_jmpOffset),
    .io_wdata_0_jalTarget      (r_2_jalTarget),
    .io_wdata_0_rvcMask_0      (r_2_rvcMask_0),
    .io_wdata_0_rvcMask_1      (r_2_rvcMask_1),
    .io_wdata_0_rvcMask_2      (r_2_rvcMask_2),
    .io_wdata_0_rvcMask_3      (r_2_rvcMask_3),
    .io_wdata_0_rvcMask_4      (r_2_rvcMask_4),
    .io_wdata_0_rvcMask_5      (r_2_rvcMask_5),
    .io_wdata_0_rvcMask_6      (r_2_rvcMask_6),
    .io_wdata_0_rvcMask_7      (r_2_rvcMask_7),
    .io_wdata_0_rvcMask_8      (r_2_rvcMask_8),
    .io_wdata_0_rvcMask_9      (r_2_rvcMask_9),
    .io_wdata_0_rvcMask_10     (r_2_rvcMask_10),
    .io_wdata_0_rvcMask_11     (r_2_rvcMask_11),
    .io_wdata_0_rvcMask_12     (r_2_rvcMask_12),
    .io_wdata_0_rvcMask_13     (r_2_rvcMask_13),
    .io_wdata_0_rvcMask_14     (r_2_rvcMask_14),
    .io_wdata_0_rvcMask_15     (r_2_rvcMask_15)
  );
  DataModule__16entry_8 dataBanks_3 (
    .clock                     (clock),
    .io_raddr_0                (raddr_dup_0_3[3:0]),
    .io_raddr_1                (raddr_dup_1_3[3:0]),
    .io_rdata_0_brMask_0       (_dataBanks_3_io_rdata_0_brMask_0),
    .io_rdata_0_brMask_1       (_dataBanks_3_io_rdata_0_brMask_1),
    .io_rdata_0_brMask_2       (_dataBanks_3_io_rdata_0_brMask_2),
    .io_rdata_0_brMask_3       (_dataBanks_3_io_rdata_0_brMask_3),
    .io_rdata_0_brMask_4       (_dataBanks_3_io_rdata_0_brMask_4),
    .io_rdata_0_brMask_5       (_dataBanks_3_io_rdata_0_brMask_5),
    .io_rdata_0_brMask_6       (_dataBanks_3_io_rdata_0_brMask_6),
    .io_rdata_0_brMask_7       (_dataBanks_3_io_rdata_0_brMask_7),
    .io_rdata_0_brMask_8       (_dataBanks_3_io_rdata_0_brMask_8),
    .io_rdata_0_brMask_9       (_dataBanks_3_io_rdata_0_brMask_9),
    .io_rdata_0_brMask_10      (_dataBanks_3_io_rdata_0_brMask_10),
    .io_rdata_0_brMask_11      (_dataBanks_3_io_rdata_0_brMask_11),
    .io_rdata_0_brMask_12      (_dataBanks_3_io_rdata_0_brMask_12),
    .io_rdata_0_brMask_13      (_dataBanks_3_io_rdata_0_brMask_13),
    .io_rdata_0_brMask_14      (_dataBanks_3_io_rdata_0_brMask_14),
    .io_rdata_0_brMask_15      (_dataBanks_3_io_rdata_0_brMask_15),
    .io_rdata_0_jmpInfo_valid  (_dataBanks_3_io_rdata_0_jmpInfo_valid),
    .io_rdata_0_jmpInfo_bits_0 (_dataBanks_3_io_rdata_0_jmpInfo_bits_0),
    .io_rdata_0_jmpInfo_bits_1 (_dataBanks_3_io_rdata_0_jmpInfo_bits_1),
    .io_rdata_0_jmpInfo_bits_2 (_dataBanks_3_io_rdata_0_jmpInfo_bits_2),
    .io_rdata_0_jmpOffset      (_dataBanks_3_io_rdata_0_jmpOffset),
    .io_rdata_0_rvcMask_0      (_dataBanks_3_io_rdata_0_rvcMask_0),
    .io_rdata_0_rvcMask_1      (_dataBanks_3_io_rdata_0_rvcMask_1),
    .io_rdata_0_rvcMask_2      (_dataBanks_3_io_rdata_0_rvcMask_2),
    .io_rdata_0_rvcMask_3      (_dataBanks_3_io_rdata_0_rvcMask_3),
    .io_rdata_0_rvcMask_4      (_dataBanks_3_io_rdata_0_rvcMask_4),
    .io_rdata_0_rvcMask_5      (_dataBanks_3_io_rdata_0_rvcMask_5),
    .io_rdata_0_rvcMask_6      (_dataBanks_3_io_rdata_0_rvcMask_6),
    .io_rdata_0_rvcMask_7      (_dataBanks_3_io_rdata_0_rvcMask_7),
    .io_rdata_0_rvcMask_8      (_dataBanks_3_io_rdata_0_rvcMask_8),
    .io_rdata_0_rvcMask_9      (_dataBanks_3_io_rdata_0_rvcMask_9),
    .io_rdata_0_rvcMask_10     (_dataBanks_3_io_rdata_0_rvcMask_10),
    .io_rdata_0_rvcMask_11     (_dataBanks_3_io_rdata_0_rvcMask_11),
    .io_rdata_0_rvcMask_12     (_dataBanks_3_io_rdata_0_rvcMask_12),
    .io_rdata_0_rvcMask_13     (_dataBanks_3_io_rdata_0_rvcMask_13),
    .io_rdata_0_rvcMask_14     (_dataBanks_3_io_rdata_0_rvcMask_14),
    .io_rdata_0_rvcMask_15     (_dataBanks_3_io_rdata_0_rvcMask_15),
    .io_rdata_1_brMask_0       (_dataBanks_3_io_rdata_1_brMask_0),
    .io_rdata_1_brMask_1       (_dataBanks_3_io_rdata_1_brMask_1),
    .io_rdata_1_brMask_2       (_dataBanks_3_io_rdata_1_brMask_2),
    .io_rdata_1_brMask_3       (_dataBanks_3_io_rdata_1_brMask_3),
    .io_rdata_1_brMask_4       (_dataBanks_3_io_rdata_1_brMask_4),
    .io_rdata_1_brMask_5       (_dataBanks_3_io_rdata_1_brMask_5),
    .io_rdata_1_brMask_6       (_dataBanks_3_io_rdata_1_brMask_6),
    .io_rdata_1_brMask_7       (_dataBanks_3_io_rdata_1_brMask_7),
    .io_rdata_1_brMask_8       (_dataBanks_3_io_rdata_1_brMask_8),
    .io_rdata_1_brMask_9       (_dataBanks_3_io_rdata_1_brMask_9),
    .io_rdata_1_brMask_10      (_dataBanks_3_io_rdata_1_brMask_10),
    .io_rdata_1_brMask_11      (_dataBanks_3_io_rdata_1_brMask_11),
    .io_rdata_1_brMask_12      (_dataBanks_3_io_rdata_1_brMask_12),
    .io_rdata_1_brMask_13      (_dataBanks_3_io_rdata_1_brMask_13),
    .io_rdata_1_brMask_14      (_dataBanks_3_io_rdata_1_brMask_14),
    .io_rdata_1_brMask_15      (_dataBanks_3_io_rdata_1_brMask_15),
    .io_rdata_1_jmpInfo_valid  (_dataBanks_3_io_rdata_1_jmpInfo_valid),
    .io_rdata_1_jmpInfo_bits_0 (_dataBanks_3_io_rdata_1_jmpInfo_bits_0),
    .io_rdata_1_jmpInfo_bits_1 (_dataBanks_3_io_rdata_1_jmpInfo_bits_1),
    .io_rdata_1_jmpInfo_bits_2 (_dataBanks_3_io_rdata_1_jmpInfo_bits_2),
    .io_rdata_1_jmpOffset      (_dataBanks_3_io_rdata_1_jmpOffset),
    .io_rdata_1_jalTarget      (_dataBanks_3_io_rdata_1_jalTarget),
    .io_rdata_1_rvcMask_0      (_dataBanks_3_io_rdata_1_rvcMask_0),
    .io_rdata_1_rvcMask_1      (_dataBanks_3_io_rdata_1_rvcMask_1),
    .io_rdata_1_rvcMask_2      (_dataBanks_3_io_rdata_1_rvcMask_2),
    .io_rdata_1_rvcMask_3      (_dataBanks_3_io_rdata_1_rvcMask_3),
    .io_rdata_1_rvcMask_4      (_dataBanks_3_io_rdata_1_rvcMask_4),
    .io_rdata_1_rvcMask_5      (_dataBanks_3_io_rdata_1_rvcMask_5),
    .io_rdata_1_rvcMask_6      (_dataBanks_3_io_rdata_1_rvcMask_6),
    .io_rdata_1_rvcMask_7      (_dataBanks_3_io_rdata_1_rvcMask_7),
    .io_rdata_1_rvcMask_8      (_dataBanks_3_io_rdata_1_rvcMask_8),
    .io_rdata_1_rvcMask_9      (_dataBanks_3_io_rdata_1_rvcMask_9),
    .io_rdata_1_rvcMask_10     (_dataBanks_3_io_rdata_1_rvcMask_10),
    .io_rdata_1_rvcMask_11     (_dataBanks_3_io_rdata_1_rvcMask_11),
    .io_rdata_1_rvcMask_12     (_dataBanks_3_io_rdata_1_rvcMask_12),
    .io_rdata_1_rvcMask_13     (_dataBanks_3_io_rdata_1_rvcMask_13),
    .io_rdata_1_rvcMask_14     (_dataBanks_3_io_rdata_1_rvcMask_14),
    .io_rdata_1_rvcMask_15     (_dataBanks_3_io_rdata_1_rvcMask_15),
    .io_wen_0                  (wen_dup_last_REG_3 & (&(waddr_dup_0_3[5:4]))),
    .io_waddr_0                (waddr_dup_0_3[3:0]),
    .io_wdata_0_brMask_0       (r_3_brMask_0),
    .io_wdata_0_brMask_1       (r_3_brMask_1),
    .io_wdata_0_brMask_2       (r_3_brMask_2),
    .io_wdata_0_brMask_3       (r_3_brMask_3),
    .io_wdata_0_brMask_4       (r_3_brMask_4),
    .io_wdata_0_brMask_5       (r_3_brMask_5),
    .io_wdata_0_brMask_6       (r_3_brMask_6),
    .io_wdata_0_brMask_7       (r_3_brMask_7),
    .io_wdata_0_brMask_8       (r_3_brMask_8),
    .io_wdata_0_brMask_9       (r_3_brMask_9),
    .io_wdata_0_brMask_10      (r_3_brMask_10),
    .io_wdata_0_brMask_11      (r_3_brMask_11),
    .io_wdata_0_brMask_12      (r_3_brMask_12),
    .io_wdata_0_brMask_13      (r_3_brMask_13),
    .io_wdata_0_brMask_14      (r_3_brMask_14),
    .io_wdata_0_brMask_15      (r_3_brMask_15),
    .io_wdata_0_jmpInfo_valid  (r_3_jmpInfo_valid),
    .io_wdata_0_jmpInfo_bits_0 (r_3_jmpInfo_bits_0),
    .io_wdata_0_jmpInfo_bits_1 (r_3_jmpInfo_bits_1),
    .io_wdata_0_jmpInfo_bits_2 (r_3_jmpInfo_bits_2),
    .io_wdata_0_jmpOffset      (r_3_jmpOffset),
    .io_wdata_0_jalTarget      (r_3_jalTarget),
    .io_wdata_0_rvcMask_0      (r_3_rvcMask_0),
    .io_wdata_0_rvcMask_1      (r_3_rvcMask_1),
    .io_wdata_0_rvcMask_2      (r_3_rvcMask_2),
    .io_wdata_0_rvcMask_3      (r_3_rvcMask_3),
    .io_wdata_0_rvcMask_4      (r_3_rvcMask_4),
    .io_wdata_0_rvcMask_5      (r_3_rvcMask_5),
    .io_wdata_0_rvcMask_6      (r_3_rvcMask_6),
    .io_wdata_0_rvcMask_7      (r_3_rvcMask_7),
    .io_wdata_0_rvcMask_8      (r_3_rvcMask_8),
    .io_wdata_0_rvcMask_9      (r_3_rvcMask_9),
    .io_wdata_0_rvcMask_10     (r_3_rvcMask_10),
    .io_wdata_0_rvcMask_11     (r_3_rvcMask_11),
    .io_wdata_0_rvcMask_12     (r_3_rvcMask_12),
    .io_wdata_0_rvcMask_13     (r_3_rvcMask_13),
    .io_wdata_0_rvcMask_14     (r_3_rvcMask_14),
    .io_wdata_0_rvcMask_15     (r_3_rvcMask_15)
  );
  assign io_rdata_0_brMask_0 =
    _io_rdata_0_T & _dataBanks_0_io_rdata_0_brMask_0 | _io_rdata_0_T_1
    & _dataBanks_1_io_rdata_0_brMask_0 | _io_rdata_0_T_2
    & _dataBanks_2_io_rdata_0_brMask_0 | (&(raddr_dup[5:4]))
    & _dataBanks_3_io_rdata_0_brMask_0;
  assign io_rdata_0_brMask_1 =
    _io_rdata_0_T & _dataBanks_0_io_rdata_0_brMask_1 | _io_rdata_0_T_1
    & _dataBanks_1_io_rdata_0_brMask_1 | _io_rdata_0_T_2
    & _dataBanks_2_io_rdata_0_brMask_1 | (&(raddr_dup[5:4]))
    & _dataBanks_3_io_rdata_0_brMask_1;
  assign io_rdata_0_brMask_2 =
    _io_rdata_0_T & _dataBanks_0_io_rdata_0_brMask_2 | _io_rdata_0_T_1
    & _dataBanks_1_io_rdata_0_brMask_2 | _io_rdata_0_T_2
    & _dataBanks_2_io_rdata_0_brMask_2 | (&(raddr_dup[5:4]))
    & _dataBanks_3_io_rdata_0_brMask_2;
  assign io_rdata_0_brMask_3 =
    _io_rdata_0_T & _dataBanks_0_io_rdata_0_brMask_3 | _io_rdata_0_T_1
    & _dataBanks_1_io_rdata_0_brMask_3 | _io_rdata_0_T_2
    & _dataBanks_2_io_rdata_0_brMask_3 | (&(raddr_dup[5:4]))
    & _dataBanks_3_io_rdata_0_brMask_3;
  assign io_rdata_0_brMask_4 =
    _io_rdata_0_T & _dataBanks_0_io_rdata_0_brMask_4 | _io_rdata_0_T_1
    & _dataBanks_1_io_rdata_0_brMask_4 | _io_rdata_0_T_2
    & _dataBanks_2_io_rdata_0_brMask_4 | (&(raddr_dup[5:4]))
    & _dataBanks_3_io_rdata_0_brMask_4;
  assign io_rdata_0_brMask_5 =
    _io_rdata_0_T & _dataBanks_0_io_rdata_0_brMask_5 | _io_rdata_0_T_1
    & _dataBanks_1_io_rdata_0_brMask_5 | _io_rdata_0_T_2
    & _dataBanks_2_io_rdata_0_brMask_5 | (&(raddr_dup[5:4]))
    & _dataBanks_3_io_rdata_0_brMask_5;
  assign io_rdata_0_brMask_6 =
    _io_rdata_0_T & _dataBanks_0_io_rdata_0_brMask_6 | _io_rdata_0_T_1
    & _dataBanks_1_io_rdata_0_brMask_6 | _io_rdata_0_T_2
    & _dataBanks_2_io_rdata_0_brMask_6 | (&(raddr_dup[5:4]))
    & _dataBanks_3_io_rdata_0_brMask_6;
  assign io_rdata_0_brMask_7 =
    _io_rdata_0_T & _dataBanks_0_io_rdata_0_brMask_7 | _io_rdata_0_T_1
    & _dataBanks_1_io_rdata_0_brMask_7 | _io_rdata_0_T_2
    & _dataBanks_2_io_rdata_0_brMask_7 | (&(raddr_dup[5:4]))
    & _dataBanks_3_io_rdata_0_brMask_7;
  assign io_rdata_0_brMask_8 =
    _io_rdata_0_T & _dataBanks_0_io_rdata_0_brMask_8 | _io_rdata_0_T_1
    & _dataBanks_1_io_rdata_0_brMask_8 | _io_rdata_0_T_2
    & _dataBanks_2_io_rdata_0_brMask_8 | (&(raddr_dup[5:4]))
    & _dataBanks_3_io_rdata_0_brMask_8;
  assign io_rdata_0_brMask_9 =
    _io_rdata_0_T & _dataBanks_0_io_rdata_0_brMask_9 | _io_rdata_0_T_1
    & _dataBanks_1_io_rdata_0_brMask_9 | _io_rdata_0_T_2
    & _dataBanks_2_io_rdata_0_brMask_9 | (&(raddr_dup[5:4]))
    & _dataBanks_3_io_rdata_0_brMask_9;
  assign io_rdata_0_brMask_10 =
    _io_rdata_0_T & _dataBanks_0_io_rdata_0_brMask_10 | _io_rdata_0_T_1
    & _dataBanks_1_io_rdata_0_brMask_10 | _io_rdata_0_T_2
    & _dataBanks_2_io_rdata_0_brMask_10 | (&(raddr_dup[5:4]))
    & _dataBanks_3_io_rdata_0_brMask_10;
  assign io_rdata_0_brMask_11 =
    _io_rdata_0_T & _dataBanks_0_io_rdata_0_brMask_11 | _io_rdata_0_T_1
    & _dataBanks_1_io_rdata_0_brMask_11 | _io_rdata_0_T_2
    & _dataBanks_2_io_rdata_0_brMask_11 | (&(raddr_dup[5:4]))
    & _dataBanks_3_io_rdata_0_brMask_11;
  assign io_rdata_0_brMask_12 =
    _io_rdata_0_T & _dataBanks_0_io_rdata_0_brMask_12 | _io_rdata_0_T_1
    & _dataBanks_1_io_rdata_0_brMask_12 | _io_rdata_0_T_2
    & _dataBanks_2_io_rdata_0_brMask_12 | (&(raddr_dup[5:4]))
    & _dataBanks_3_io_rdata_0_brMask_12;
  assign io_rdata_0_brMask_13 =
    _io_rdata_0_T & _dataBanks_0_io_rdata_0_brMask_13 | _io_rdata_0_T_1
    & _dataBanks_1_io_rdata_0_brMask_13 | _io_rdata_0_T_2
    & _dataBanks_2_io_rdata_0_brMask_13 | (&(raddr_dup[5:4]))
    & _dataBanks_3_io_rdata_0_brMask_13;
  assign io_rdata_0_brMask_14 =
    _io_rdata_0_T & _dataBanks_0_io_rdata_0_brMask_14 | _io_rdata_0_T_1
    & _dataBanks_1_io_rdata_0_brMask_14 | _io_rdata_0_T_2
    & _dataBanks_2_io_rdata_0_brMask_14 | (&(raddr_dup[5:4]))
    & _dataBanks_3_io_rdata_0_brMask_14;
  assign io_rdata_0_brMask_15 =
    _io_rdata_0_T & _dataBanks_0_io_rdata_0_brMask_15 | _io_rdata_0_T_1
    & _dataBanks_1_io_rdata_0_brMask_15 | _io_rdata_0_T_2
    & _dataBanks_2_io_rdata_0_brMask_15 | (&(raddr_dup[5:4]))
    & _dataBanks_3_io_rdata_0_brMask_15;
  assign io_rdata_0_jmpInfo_valid =
    _io_rdata_0_T & _dataBanks_0_io_rdata_0_jmpInfo_valid | _io_rdata_0_T_1
    & _dataBanks_1_io_rdata_0_jmpInfo_valid | _io_rdata_0_T_2
    & _dataBanks_2_io_rdata_0_jmpInfo_valid | (&(raddr_dup[5:4]))
    & _dataBanks_3_io_rdata_0_jmpInfo_valid;
  assign io_rdata_0_jmpInfo_bits_0 =
    _io_rdata_0_T & _dataBanks_0_io_rdata_0_jmpInfo_bits_0 | _io_rdata_0_T_1
    & _dataBanks_1_io_rdata_0_jmpInfo_bits_0 | _io_rdata_0_T_2
    & _dataBanks_2_io_rdata_0_jmpInfo_bits_0 | (&(raddr_dup[5:4]))
    & _dataBanks_3_io_rdata_0_jmpInfo_bits_0;
  assign io_rdata_0_jmpInfo_bits_1 =
    _io_rdata_0_T & _dataBanks_0_io_rdata_0_jmpInfo_bits_1 | _io_rdata_0_T_1
    & _dataBanks_1_io_rdata_0_jmpInfo_bits_1 | _io_rdata_0_T_2
    & _dataBanks_2_io_rdata_0_jmpInfo_bits_1 | (&(raddr_dup[5:4]))
    & _dataBanks_3_io_rdata_0_jmpInfo_bits_1;
  assign io_rdata_0_jmpInfo_bits_2 =
    _io_rdata_0_T & _dataBanks_0_io_rdata_0_jmpInfo_bits_2 | _io_rdata_0_T_1
    & _dataBanks_1_io_rdata_0_jmpInfo_bits_2 | _io_rdata_0_T_2
    & _dataBanks_2_io_rdata_0_jmpInfo_bits_2 | (&(raddr_dup[5:4]))
    & _dataBanks_3_io_rdata_0_jmpInfo_bits_2;
  assign io_rdata_0_jmpOffset =
    (_io_rdata_0_T ? _dataBanks_0_io_rdata_0_jmpOffset : 4'h0)
    | (_io_rdata_0_T_1 ? _dataBanks_1_io_rdata_0_jmpOffset : 4'h0)
    | (_io_rdata_0_T_2 ? _dataBanks_2_io_rdata_0_jmpOffset : 4'h0)
    | ((&(raddr_dup[5:4])) ? _dataBanks_3_io_rdata_0_jmpOffset : 4'h0);
  assign io_rdata_0_rvcMask_0 =
    _io_rdata_0_T & _dataBanks_0_io_rdata_0_rvcMask_0 | _io_rdata_0_T_1
    & _dataBanks_1_io_rdata_0_rvcMask_0 | _io_rdata_0_T_2
    & _dataBanks_2_io_rdata_0_rvcMask_0 | (&(raddr_dup[5:4]))
    & _dataBanks_3_io_rdata_0_rvcMask_0;
  assign io_rdata_0_rvcMask_1 =
    _io_rdata_0_T & _dataBanks_0_io_rdata_0_rvcMask_1 | _io_rdata_0_T_1
    & _dataBanks_1_io_rdata_0_rvcMask_1 | _io_rdata_0_T_2
    & _dataBanks_2_io_rdata_0_rvcMask_1 | (&(raddr_dup[5:4]))
    & _dataBanks_3_io_rdata_0_rvcMask_1;
  assign io_rdata_0_rvcMask_2 =
    _io_rdata_0_T & _dataBanks_0_io_rdata_0_rvcMask_2 | _io_rdata_0_T_1
    & _dataBanks_1_io_rdata_0_rvcMask_2 | _io_rdata_0_T_2
    & _dataBanks_2_io_rdata_0_rvcMask_2 | (&(raddr_dup[5:4]))
    & _dataBanks_3_io_rdata_0_rvcMask_2;
  assign io_rdata_0_rvcMask_3 =
    _io_rdata_0_T & _dataBanks_0_io_rdata_0_rvcMask_3 | _io_rdata_0_T_1
    & _dataBanks_1_io_rdata_0_rvcMask_3 | _io_rdata_0_T_2
    & _dataBanks_2_io_rdata_0_rvcMask_3 | (&(raddr_dup[5:4]))
    & _dataBanks_3_io_rdata_0_rvcMask_3;
  assign io_rdata_0_rvcMask_4 =
    _io_rdata_0_T & _dataBanks_0_io_rdata_0_rvcMask_4 | _io_rdata_0_T_1
    & _dataBanks_1_io_rdata_0_rvcMask_4 | _io_rdata_0_T_2
    & _dataBanks_2_io_rdata_0_rvcMask_4 | (&(raddr_dup[5:4]))
    & _dataBanks_3_io_rdata_0_rvcMask_4;
  assign io_rdata_0_rvcMask_5 =
    _io_rdata_0_T & _dataBanks_0_io_rdata_0_rvcMask_5 | _io_rdata_0_T_1
    & _dataBanks_1_io_rdata_0_rvcMask_5 | _io_rdata_0_T_2
    & _dataBanks_2_io_rdata_0_rvcMask_5 | (&(raddr_dup[5:4]))
    & _dataBanks_3_io_rdata_0_rvcMask_5;
  assign io_rdata_0_rvcMask_6 =
    _io_rdata_0_T & _dataBanks_0_io_rdata_0_rvcMask_6 | _io_rdata_0_T_1
    & _dataBanks_1_io_rdata_0_rvcMask_6 | _io_rdata_0_T_2
    & _dataBanks_2_io_rdata_0_rvcMask_6 | (&(raddr_dup[5:4]))
    & _dataBanks_3_io_rdata_0_rvcMask_6;
  assign io_rdata_0_rvcMask_7 =
    _io_rdata_0_T & _dataBanks_0_io_rdata_0_rvcMask_7 | _io_rdata_0_T_1
    & _dataBanks_1_io_rdata_0_rvcMask_7 | _io_rdata_0_T_2
    & _dataBanks_2_io_rdata_0_rvcMask_7 | (&(raddr_dup[5:4]))
    & _dataBanks_3_io_rdata_0_rvcMask_7;
  assign io_rdata_0_rvcMask_8 =
    _io_rdata_0_T & _dataBanks_0_io_rdata_0_rvcMask_8 | _io_rdata_0_T_1
    & _dataBanks_1_io_rdata_0_rvcMask_8 | _io_rdata_0_T_2
    & _dataBanks_2_io_rdata_0_rvcMask_8 | (&(raddr_dup[5:4]))
    & _dataBanks_3_io_rdata_0_rvcMask_8;
  assign io_rdata_0_rvcMask_9 =
    _io_rdata_0_T & _dataBanks_0_io_rdata_0_rvcMask_9 | _io_rdata_0_T_1
    & _dataBanks_1_io_rdata_0_rvcMask_9 | _io_rdata_0_T_2
    & _dataBanks_2_io_rdata_0_rvcMask_9 | (&(raddr_dup[5:4]))
    & _dataBanks_3_io_rdata_0_rvcMask_9;
  assign io_rdata_0_rvcMask_10 =
    _io_rdata_0_T & _dataBanks_0_io_rdata_0_rvcMask_10 | _io_rdata_0_T_1
    & _dataBanks_1_io_rdata_0_rvcMask_10 | _io_rdata_0_T_2
    & _dataBanks_2_io_rdata_0_rvcMask_10 | (&(raddr_dup[5:4]))
    & _dataBanks_3_io_rdata_0_rvcMask_10;
  assign io_rdata_0_rvcMask_11 =
    _io_rdata_0_T & _dataBanks_0_io_rdata_0_rvcMask_11 | _io_rdata_0_T_1
    & _dataBanks_1_io_rdata_0_rvcMask_11 | _io_rdata_0_T_2
    & _dataBanks_2_io_rdata_0_rvcMask_11 | (&(raddr_dup[5:4]))
    & _dataBanks_3_io_rdata_0_rvcMask_11;
  assign io_rdata_0_rvcMask_12 =
    _io_rdata_0_T & _dataBanks_0_io_rdata_0_rvcMask_12 | _io_rdata_0_T_1
    & _dataBanks_1_io_rdata_0_rvcMask_12 | _io_rdata_0_T_2
    & _dataBanks_2_io_rdata_0_rvcMask_12 | (&(raddr_dup[5:4]))
    & _dataBanks_3_io_rdata_0_rvcMask_12;
  assign io_rdata_0_rvcMask_13 =
    _io_rdata_0_T & _dataBanks_0_io_rdata_0_rvcMask_13 | _io_rdata_0_T_1
    & _dataBanks_1_io_rdata_0_rvcMask_13 | _io_rdata_0_T_2
    & _dataBanks_2_io_rdata_0_rvcMask_13 | (&(raddr_dup[5:4]))
    & _dataBanks_3_io_rdata_0_rvcMask_13;
  assign io_rdata_0_rvcMask_14 =
    _io_rdata_0_T & _dataBanks_0_io_rdata_0_rvcMask_14 | _io_rdata_0_T_1
    & _dataBanks_1_io_rdata_0_rvcMask_14 | _io_rdata_0_T_2
    & _dataBanks_2_io_rdata_0_rvcMask_14 | (&(raddr_dup[5:4]))
    & _dataBanks_3_io_rdata_0_rvcMask_14;
  assign io_rdata_0_rvcMask_15 =
    _io_rdata_0_T & _dataBanks_0_io_rdata_0_rvcMask_15 | _io_rdata_0_T_1
    & _dataBanks_1_io_rdata_0_rvcMask_15 | _io_rdata_0_T_2
    & _dataBanks_2_io_rdata_0_rvcMask_15 | (&(raddr_dup[5:4]))
    & _dataBanks_3_io_rdata_0_rvcMask_15;
  assign io_rdata_1_brMask_0 =
    _io_rdata_1_T & _dataBanks_0_io_rdata_1_brMask_0 | _io_rdata_1_T_1
    & _dataBanks_1_io_rdata_1_brMask_0 | _io_rdata_1_T_2
    & _dataBanks_2_io_rdata_1_brMask_0 | (&(raddr_dup_2[5:4]))
    & _dataBanks_3_io_rdata_1_brMask_0;
  assign io_rdata_1_brMask_1 =
    _io_rdata_1_T & _dataBanks_0_io_rdata_1_brMask_1 | _io_rdata_1_T_1
    & _dataBanks_1_io_rdata_1_brMask_1 | _io_rdata_1_T_2
    & _dataBanks_2_io_rdata_1_brMask_1 | (&(raddr_dup_2[5:4]))
    & _dataBanks_3_io_rdata_1_brMask_1;
  assign io_rdata_1_brMask_2 =
    _io_rdata_1_T & _dataBanks_0_io_rdata_1_brMask_2 | _io_rdata_1_T_1
    & _dataBanks_1_io_rdata_1_brMask_2 | _io_rdata_1_T_2
    & _dataBanks_2_io_rdata_1_brMask_2 | (&(raddr_dup_2[5:4]))
    & _dataBanks_3_io_rdata_1_brMask_2;
  assign io_rdata_1_brMask_3 =
    _io_rdata_1_T & _dataBanks_0_io_rdata_1_brMask_3 | _io_rdata_1_T_1
    & _dataBanks_1_io_rdata_1_brMask_3 | _io_rdata_1_T_2
    & _dataBanks_2_io_rdata_1_brMask_3 | (&(raddr_dup_2[5:4]))
    & _dataBanks_3_io_rdata_1_brMask_3;
  assign io_rdata_1_brMask_4 =
    _io_rdata_1_T & _dataBanks_0_io_rdata_1_brMask_4 | _io_rdata_1_T_1
    & _dataBanks_1_io_rdata_1_brMask_4 | _io_rdata_1_T_2
    & _dataBanks_2_io_rdata_1_brMask_4 | (&(raddr_dup_2[5:4]))
    & _dataBanks_3_io_rdata_1_brMask_4;
  assign io_rdata_1_brMask_5 =
    _io_rdata_1_T & _dataBanks_0_io_rdata_1_brMask_5 | _io_rdata_1_T_1
    & _dataBanks_1_io_rdata_1_brMask_5 | _io_rdata_1_T_2
    & _dataBanks_2_io_rdata_1_brMask_5 | (&(raddr_dup_2[5:4]))
    & _dataBanks_3_io_rdata_1_brMask_5;
  assign io_rdata_1_brMask_6 =
    _io_rdata_1_T & _dataBanks_0_io_rdata_1_brMask_6 | _io_rdata_1_T_1
    & _dataBanks_1_io_rdata_1_brMask_6 | _io_rdata_1_T_2
    & _dataBanks_2_io_rdata_1_brMask_6 | (&(raddr_dup_2[5:4]))
    & _dataBanks_3_io_rdata_1_brMask_6;
  assign io_rdata_1_brMask_7 =
    _io_rdata_1_T & _dataBanks_0_io_rdata_1_brMask_7 | _io_rdata_1_T_1
    & _dataBanks_1_io_rdata_1_brMask_7 | _io_rdata_1_T_2
    & _dataBanks_2_io_rdata_1_brMask_7 | (&(raddr_dup_2[5:4]))
    & _dataBanks_3_io_rdata_1_brMask_7;
  assign io_rdata_1_brMask_8 =
    _io_rdata_1_T & _dataBanks_0_io_rdata_1_brMask_8 | _io_rdata_1_T_1
    & _dataBanks_1_io_rdata_1_brMask_8 | _io_rdata_1_T_2
    & _dataBanks_2_io_rdata_1_brMask_8 | (&(raddr_dup_2[5:4]))
    & _dataBanks_3_io_rdata_1_brMask_8;
  assign io_rdata_1_brMask_9 =
    _io_rdata_1_T & _dataBanks_0_io_rdata_1_brMask_9 | _io_rdata_1_T_1
    & _dataBanks_1_io_rdata_1_brMask_9 | _io_rdata_1_T_2
    & _dataBanks_2_io_rdata_1_brMask_9 | (&(raddr_dup_2[5:4]))
    & _dataBanks_3_io_rdata_1_brMask_9;
  assign io_rdata_1_brMask_10 =
    _io_rdata_1_T & _dataBanks_0_io_rdata_1_brMask_10 | _io_rdata_1_T_1
    & _dataBanks_1_io_rdata_1_brMask_10 | _io_rdata_1_T_2
    & _dataBanks_2_io_rdata_1_brMask_10 | (&(raddr_dup_2[5:4]))
    & _dataBanks_3_io_rdata_1_brMask_10;
  assign io_rdata_1_brMask_11 =
    _io_rdata_1_T & _dataBanks_0_io_rdata_1_brMask_11 | _io_rdata_1_T_1
    & _dataBanks_1_io_rdata_1_brMask_11 | _io_rdata_1_T_2
    & _dataBanks_2_io_rdata_1_brMask_11 | (&(raddr_dup_2[5:4]))
    & _dataBanks_3_io_rdata_1_brMask_11;
  assign io_rdata_1_brMask_12 =
    _io_rdata_1_T & _dataBanks_0_io_rdata_1_brMask_12 | _io_rdata_1_T_1
    & _dataBanks_1_io_rdata_1_brMask_12 | _io_rdata_1_T_2
    & _dataBanks_2_io_rdata_1_brMask_12 | (&(raddr_dup_2[5:4]))
    & _dataBanks_3_io_rdata_1_brMask_12;
  assign io_rdata_1_brMask_13 =
    _io_rdata_1_T & _dataBanks_0_io_rdata_1_brMask_13 | _io_rdata_1_T_1
    & _dataBanks_1_io_rdata_1_brMask_13 | _io_rdata_1_T_2
    & _dataBanks_2_io_rdata_1_brMask_13 | (&(raddr_dup_2[5:4]))
    & _dataBanks_3_io_rdata_1_brMask_13;
  assign io_rdata_1_brMask_14 =
    _io_rdata_1_T & _dataBanks_0_io_rdata_1_brMask_14 | _io_rdata_1_T_1
    & _dataBanks_1_io_rdata_1_brMask_14 | _io_rdata_1_T_2
    & _dataBanks_2_io_rdata_1_brMask_14 | (&(raddr_dup_2[5:4]))
    & _dataBanks_3_io_rdata_1_brMask_14;
  assign io_rdata_1_brMask_15 =
    _io_rdata_1_T & _dataBanks_0_io_rdata_1_brMask_15 | _io_rdata_1_T_1
    & _dataBanks_1_io_rdata_1_brMask_15 | _io_rdata_1_T_2
    & _dataBanks_2_io_rdata_1_brMask_15 | (&(raddr_dup_2[5:4]))
    & _dataBanks_3_io_rdata_1_brMask_15;
  assign io_rdata_1_jmpInfo_valid =
    _io_rdata_1_T & _dataBanks_0_io_rdata_1_jmpInfo_valid | _io_rdata_1_T_1
    & _dataBanks_1_io_rdata_1_jmpInfo_valid | _io_rdata_1_T_2
    & _dataBanks_2_io_rdata_1_jmpInfo_valid | (&(raddr_dup_2[5:4]))
    & _dataBanks_3_io_rdata_1_jmpInfo_valid;
  assign io_rdata_1_jmpInfo_bits_0 =
    _io_rdata_1_T & _dataBanks_0_io_rdata_1_jmpInfo_bits_0 | _io_rdata_1_T_1
    & _dataBanks_1_io_rdata_1_jmpInfo_bits_0 | _io_rdata_1_T_2
    & _dataBanks_2_io_rdata_1_jmpInfo_bits_0 | (&(raddr_dup_2[5:4]))
    & _dataBanks_3_io_rdata_1_jmpInfo_bits_0;
  assign io_rdata_1_jmpInfo_bits_1 =
    _io_rdata_1_T & _dataBanks_0_io_rdata_1_jmpInfo_bits_1 | _io_rdata_1_T_1
    & _dataBanks_1_io_rdata_1_jmpInfo_bits_1 | _io_rdata_1_T_2
    & _dataBanks_2_io_rdata_1_jmpInfo_bits_1 | (&(raddr_dup_2[5:4]))
    & _dataBanks_3_io_rdata_1_jmpInfo_bits_1;
  assign io_rdata_1_jmpInfo_bits_2 =
    _io_rdata_1_T & _dataBanks_0_io_rdata_1_jmpInfo_bits_2 | _io_rdata_1_T_1
    & _dataBanks_1_io_rdata_1_jmpInfo_bits_2 | _io_rdata_1_T_2
    & _dataBanks_2_io_rdata_1_jmpInfo_bits_2 | (&(raddr_dup_2[5:4]))
    & _dataBanks_3_io_rdata_1_jmpInfo_bits_2;
  assign io_rdata_1_jmpOffset =
    (_io_rdata_1_T ? _dataBanks_0_io_rdata_1_jmpOffset : 4'h0)
    | (_io_rdata_1_T_1 ? _dataBanks_1_io_rdata_1_jmpOffset : 4'h0)
    | (_io_rdata_1_T_2 ? _dataBanks_2_io_rdata_1_jmpOffset : 4'h0)
    | ((&(raddr_dup_2[5:4])) ? _dataBanks_3_io_rdata_1_jmpOffset : 4'h0);
  assign io_rdata_1_jalTarget =
    (_io_rdata_1_T ? _dataBanks_0_io_rdata_1_jalTarget : 50'h0)
    | (_io_rdata_1_T_1 ? _dataBanks_1_io_rdata_1_jalTarget : 50'h0)
    | (_io_rdata_1_T_2 ? _dataBanks_2_io_rdata_1_jalTarget : 50'h0)
    | ((&(raddr_dup_2[5:4])) ? _dataBanks_3_io_rdata_1_jalTarget : 50'h0);
  assign io_rdata_1_rvcMask_0 =
    _io_rdata_1_T & _dataBanks_0_io_rdata_1_rvcMask_0 | _io_rdata_1_T_1
    & _dataBanks_1_io_rdata_1_rvcMask_0 | _io_rdata_1_T_2
    & _dataBanks_2_io_rdata_1_rvcMask_0 | (&(raddr_dup_2[5:4]))
    & _dataBanks_3_io_rdata_1_rvcMask_0;
  assign io_rdata_1_rvcMask_1 =
    _io_rdata_1_T & _dataBanks_0_io_rdata_1_rvcMask_1 | _io_rdata_1_T_1
    & _dataBanks_1_io_rdata_1_rvcMask_1 | _io_rdata_1_T_2
    & _dataBanks_2_io_rdata_1_rvcMask_1 | (&(raddr_dup_2[5:4]))
    & _dataBanks_3_io_rdata_1_rvcMask_1;
  assign io_rdata_1_rvcMask_2 =
    _io_rdata_1_T & _dataBanks_0_io_rdata_1_rvcMask_2 | _io_rdata_1_T_1
    & _dataBanks_1_io_rdata_1_rvcMask_2 | _io_rdata_1_T_2
    & _dataBanks_2_io_rdata_1_rvcMask_2 | (&(raddr_dup_2[5:4]))
    & _dataBanks_3_io_rdata_1_rvcMask_2;
  assign io_rdata_1_rvcMask_3 =
    _io_rdata_1_T & _dataBanks_0_io_rdata_1_rvcMask_3 | _io_rdata_1_T_1
    & _dataBanks_1_io_rdata_1_rvcMask_3 | _io_rdata_1_T_2
    & _dataBanks_2_io_rdata_1_rvcMask_3 | (&(raddr_dup_2[5:4]))
    & _dataBanks_3_io_rdata_1_rvcMask_3;
  assign io_rdata_1_rvcMask_4 =
    _io_rdata_1_T & _dataBanks_0_io_rdata_1_rvcMask_4 | _io_rdata_1_T_1
    & _dataBanks_1_io_rdata_1_rvcMask_4 | _io_rdata_1_T_2
    & _dataBanks_2_io_rdata_1_rvcMask_4 | (&(raddr_dup_2[5:4]))
    & _dataBanks_3_io_rdata_1_rvcMask_4;
  assign io_rdata_1_rvcMask_5 =
    _io_rdata_1_T & _dataBanks_0_io_rdata_1_rvcMask_5 | _io_rdata_1_T_1
    & _dataBanks_1_io_rdata_1_rvcMask_5 | _io_rdata_1_T_2
    & _dataBanks_2_io_rdata_1_rvcMask_5 | (&(raddr_dup_2[5:4]))
    & _dataBanks_3_io_rdata_1_rvcMask_5;
  assign io_rdata_1_rvcMask_6 =
    _io_rdata_1_T & _dataBanks_0_io_rdata_1_rvcMask_6 | _io_rdata_1_T_1
    & _dataBanks_1_io_rdata_1_rvcMask_6 | _io_rdata_1_T_2
    & _dataBanks_2_io_rdata_1_rvcMask_6 | (&(raddr_dup_2[5:4]))
    & _dataBanks_3_io_rdata_1_rvcMask_6;
  assign io_rdata_1_rvcMask_7 =
    _io_rdata_1_T & _dataBanks_0_io_rdata_1_rvcMask_7 | _io_rdata_1_T_1
    & _dataBanks_1_io_rdata_1_rvcMask_7 | _io_rdata_1_T_2
    & _dataBanks_2_io_rdata_1_rvcMask_7 | (&(raddr_dup_2[5:4]))
    & _dataBanks_3_io_rdata_1_rvcMask_7;
  assign io_rdata_1_rvcMask_8 =
    _io_rdata_1_T & _dataBanks_0_io_rdata_1_rvcMask_8 | _io_rdata_1_T_1
    & _dataBanks_1_io_rdata_1_rvcMask_8 | _io_rdata_1_T_2
    & _dataBanks_2_io_rdata_1_rvcMask_8 | (&(raddr_dup_2[5:4]))
    & _dataBanks_3_io_rdata_1_rvcMask_8;
  assign io_rdata_1_rvcMask_9 =
    _io_rdata_1_T & _dataBanks_0_io_rdata_1_rvcMask_9 | _io_rdata_1_T_1
    & _dataBanks_1_io_rdata_1_rvcMask_9 | _io_rdata_1_T_2
    & _dataBanks_2_io_rdata_1_rvcMask_9 | (&(raddr_dup_2[5:4]))
    & _dataBanks_3_io_rdata_1_rvcMask_9;
  assign io_rdata_1_rvcMask_10 =
    _io_rdata_1_T & _dataBanks_0_io_rdata_1_rvcMask_10 | _io_rdata_1_T_1
    & _dataBanks_1_io_rdata_1_rvcMask_10 | _io_rdata_1_T_2
    & _dataBanks_2_io_rdata_1_rvcMask_10 | (&(raddr_dup_2[5:4]))
    & _dataBanks_3_io_rdata_1_rvcMask_10;
  assign io_rdata_1_rvcMask_11 =
    _io_rdata_1_T & _dataBanks_0_io_rdata_1_rvcMask_11 | _io_rdata_1_T_1
    & _dataBanks_1_io_rdata_1_rvcMask_11 | _io_rdata_1_T_2
    & _dataBanks_2_io_rdata_1_rvcMask_11 | (&(raddr_dup_2[5:4]))
    & _dataBanks_3_io_rdata_1_rvcMask_11;
  assign io_rdata_1_rvcMask_12 =
    _io_rdata_1_T & _dataBanks_0_io_rdata_1_rvcMask_12 | _io_rdata_1_T_1
    & _dataBanks_1_io_rdata_1_rvcMask_12 | _io_rdata_1_T_2
    & _dataBanks_2_io_rdata_1_rvcMask_12 | (&(raddr_dup_2[5:4]))
    & _dataBanks_3_io_rdata_1_rvcMask_12;
  assign io_rdata_1_rvcMask_13 =
    _io_rdata_1_T & _dataBanks_0_io_rdata_1_rvcMask_13 | _io_rdata_1_T_1
    & _dataBanks_1_io_rdata_1_rvcMask_13 | _io_rdata_1_T_2
    & _dataBanks_2_io_rdata_1_rvcMask_13 | (&(raddr_dup_2[5:4]))
    & _dataBanks_3_io_rdata_1_rvcMask_13;
  assign io_rdata_1_rvcMask_14 =
    _io_rdata_1_T & _dataBanks_0_io_rdata_1_rvcMask_14 | _io_rdata_1_T_1
    & _dataBanks_1_io_rdata_1_rvcMask_14 | _io_rdata_1_T_2
    & _dataBanks_2_io_rdata_1_rvcMask_14 | (&(raddr_dup_2[5:4]))
    & _dataBanks_3_io_rdata_1_rvcMask_14;
  assign io_rdata_1_rvcMask_15 =
    _io_rdata_1_T & _dataBanks_0_io_rdata_1_rvcMask_15 | _io_rdata_1_T_1
    & _dataBanks_1_io_rdata_1_rvcMask_15 | _io_rdata_1_T_2
    & _dataBanks_2_io_rdata_1_rvcMask_15 | (&(raddr_dup_2[5:4]))
    & _dataBanks_3_io_rdata_1_rvcMask_15;
endmodule

