# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.2.0
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _UT_FtqPdMem
else:
    import _UT_FtqPdMem

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


import weakref

class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _UT_FtqPdMem.delete_SwigPyIterator

    def value(self):
        return _UT_FtqPdMem.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _UT_FtqPdMem.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _UT_FtqPdMem.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _UT_FtqPdMem.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _UT_FtqPdMem.SwigPyIterator_equal(self, x)

    def copy(self):
        return _UT_FtqPdMem.SwigPyIterator_copy(self)

    def next(self):
        return _UT_FtqPdMem.SwigPyIterator_next(self)

    def __next__(self):
        return _UT_FtqPdMem.SwigPyIterator___next__(self)

    def previous(self):
        return _UT_FtqPdMem.SwigPyIterator_previous(self)

    def advance(self, n):
        return _UT_FtqPdMem.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _UT_FtqPdMem.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _UT_FtqPdMem.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _UT_FtqPdMem.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _UT_FtqPdMem.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _UT_FtqPdMem.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _UT_FtqPdMem.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _UT_FtqPdMem:
_UT_FtqPdMem.SwigPyIterator_swigregister(SwigPyIterator)
class StringVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _UT_FtqPdMem.StringVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _UT_FtqPdMem.StringVector___nonzero__(self)

    def __bool__(self):
        return _UT_FtqPdMem.StringVector___bool__(self)

    def __len__(self):
        return _UT_FtqPdMem.StringVector___len__(self)

    def __getslice__(self, i, j):
        return _UT_FtqPdMem.StringVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _UT_FtqPdMem.StringVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _UT_FtqPdMem.StringVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _UT_FtqPdMem.StringVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _UT_FtqPdMem.StringVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _UT_FtqPdMem.StringVector___setitem__(self, *args)

    def pop(self):
        return _UT_FtqPdMem.StringVector_pop(self)

    def append(self, x):
        return _UT_FtqPdMem.StringVector_append(self, x)

    def empty(self):
        return _UT_FtqPdMem.StringVector_empty(self)

    def size(self):
        return _UT_FtqPdMem.StringVector_size(self)

    def swap(self, v):
        return _UT_FtqPdMem.StringVector_swap(self, v)

    def begin(self):
        return _UT_FtqPdMem.StringVector_begin(self)

    def end(self):
        return _UT_FtqPdMem.StringVector_end(self)

    def rbegin(self):
        return _UT_FtqPdMem.StringVector_rbegin(self)

    def rend(self):
        return _UT_FtqPdMem.StringVector_rend(self)

    def clear(self):
        return _UT_FtqPdMem.StringVector_clear(self)

    def get_allocator(self):
        return _UT_FtqPdMem.StringVector_get_allocator(self)

    def pop_back(self):
        return _UT_FtqPdMem.StringVector_pop_back(self)

    def erase(self, *args):
        return _UT_FtqPdMem.StringVector_erase(self, *args)

    def __init__(self, *args):
        _UT_FtqPdMem.StringVector_swiginit(self, _UT_FtqPdMem.new_StringVector(*args))

    def push_back(self, x):
        return _UT_FtqPdMem.StringVector_push_back(self, x)

    def front(self):
        return _UT_FtqPdMem.StringVector_front(self)

    def back(self):
        return _UT_FtqPdMem.StringVector_back(self)

    def assign(self, n, x):
        return _UT_FtqPdMem.StringVector_assign(self, n, x)

    def resize(self, *args):
        return _UT_FtqPdMem.StringVector_resize(self, *args)

    def insert(self, *args):
        return _UT_FtqPdMem.StringVector_insert(self, *args)

    def reserve(self, n):
        return _UT_FtqPdMem.StringVector_reserve(self, n)

    def capacity(self):
        return _UT_FtqPdMem.StringVector_capacity(self)
    __swig_destroy__ = _UT_FtqPdMem.delete_StringVector

# Register StringVector in _UT_FtqPdMem:
_UT_FtqPdMem.StringVector_swigregister(StringVector)
class DutBase(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    cycle = property(_UT_FtqPdMem.DutBase_cycle_get, _UT_FtqPdMem.DutBase_cycle_set)
    argc = property(_UT_FtqPdMem.DutBase_argc_get, _UT_FtqPdMem.DutBase_argc_set)
    argv = property(_UT_FtqPdMem.DutBase_argv_get, _UT_FtqPdMem.DutBase_argv_set)
    __swig_destroy__ = _UT_FtqPdMem.delete_DutBase

    def Step(self, cycle, dump):
        return _UT_FtqPdMem.DutBase_Step(self, cycle, dump)

    def Finish(self):
        return _UT_FtqPdMem.DutBase_Finish(self)

    def SetWaveform(self, filename):
        return _UT_FtqPdMem.DutBase_SetWaveform(self, filename)

    def FlushWaveform(self):
        return _UT_FtqPdMem.DutBase_FlushWaveform(self)

    def WaveformEnable(self, enable):
        return _UT_FtqPdMem.DutBase_WaveformEnable(self, enable)

    def SetCoverage(self, filename):
        return _UT_FtqPdMem.DutBase_SetCoverage(self, filename)

    def CheckPoint(self, filename):
        return _UT_FtqPdMem.DutBase_CheckPoint(self, filename)

    def Restore(self, filename):
        return _UT_FtqPdMem.DutBase_Restore(self, filename)

# Register DutBase in _UT_FtqPdMem:
_UT_FtqPdMem.DutBase_swigregister(DutBase)
class DutVerilatorBase(DutBase):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    sv_scope = property(_UT_FtqPdMem.DutVerilatorBase_sv_scope_get, _UT_FtqPdMem.DutVerilatorBase_sv_scope_set)
    top = property(_UT_FtqPdMem.DutVerilatorBase_top_get, _UT_FtqPdMem.DutVerilatorBase_top_set)

    def init(self, arg2, arg3):
        return _UT_FtqPdMem.DutVerilatorBase_init(self, arg2, arg3)

    def __init__(self, *args):
        _UT_FtqPdMem.DutVerilatorBase_swiginit(self, _UT_FtqPdMem.new_DutVerilatorBase(*args))
    __swig_destroy__ = _UT_FtqPdMem.delete_DutVerilatorBase

    def Step(self, cycle, dump):
        return _UT_FtqPdMem.DutVerilatorBase_Step(self, cycle, dump)

    def Finish(self):
        return _UT_FtqPdMem.DutVerilatorBase_Finish(self)

    def SetWaveform(self, filename):
        return _UT_FtqPdMem.DutVerilatorBase_SetWaveform(self, filename)

    def FlushWaveform(self):
        return _UT_FtqPdMem.DutVerilatorBase_FlushWaveform(self)

    def WaveformEnable(self, enable):
        return _UT_FtqPdMem.DutVerilatorBase_WaveformEnable(self, enable)

    def SetCoverage(self, filename):
        return _UT_FtqPdMem.DutVerilatorBase_SetCoverage(self, filename)

    def CheckPoint(self, filename):
        return _UT_FtqPdMem.DutVerilatorBase_CheckPoint(self, filename)

    def Restore(self, filename):
        return _UT_FtqPdMem.DutVerilatorBase_Restore(self, filename)

# Register DutVerilatorBase in _UT_FtqPdMem:
_UT_FtqPdMem.DutVerilatorBase_swigregister(DutVerilatorBase)

def dlcreates(argc, argv):
    return _UT_FtqPdMem.dlcreates(argc, argv)

def dlstep(dut, ncycle, dump):
    return _UT_FtqPdMem.dlstep(dut, ncycle, dump)

def locateLibPath():
    return _UT_FtqPdMem.locateLibPath()
class DutUnifiedBase(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _UT_FtqPdMem.DutUnifiedBase_swiginit(self, _UT_FtqPdMem.new_DutUnifiedBase(*args))
    __swig_destroy__ = _UT_FtqPdMem.delete_DutUnifiedBase

    def init(self, arg2, arg3):
        return _UT_FtqPdMem.DutUnifiedBase_init(self, arg2, arg3)

    def stepNoDump(self):
        return _UT_FtqPdMem.DutUnifiedBase_stepNoDump(self)

    def simStep(self, *args):
        return _UT_FtqPdMem.DutUnifiedBase_simStep(self, *args)

    def RefreshComb(self):
        return _UT_FtqPdMem.DutUnifiedBase_RefreshComb(self)

    def Finish(self):
        return _UT_FtqPdMem.DutUnifiedBase_Finish(self)

    def GetDPIHandle(self, *args):
        return _UT_FtqPdMem.DutUnifiedBase_GetDPIHandle(self, *args)

    def GetVPIFuncPtr(self, *args):
        return _UT_FtqPdMem.DutUnifiedBase_GetVPIFuncPtr(self, *args)

    def GetVPIHandleObj(self, *args):
        return _UT_FtqPdMem.DutUnifiedBase_GetVPIHandleObj(self, *args)

    def VPIInternalSignalList(self, *args):
        return _UT_FtqPdMem.DutUnifiedBase_VPIInternalSignalList(self, *args)

    def SetWaveform(self, *args):
        return _UT_FtqPdMem.DutUnifiedBase_SetWaveform(self, *args)

    def FlushWaveform(self):
        return _UT_FtqPdMem.DutUnifiedBase_FlushWaveform(self)

    def WaveformEnable(self, enable=True):
        return _UT_FtqPdMem.DutUnifiedBase_WaveformEnable(self, enable)

    def SetCoverage(self, *args):
        return _UT_FtqPdMem.DutUnifiedBase_SetCoverage(self, *args)

    def CheckPoint(self, *args):
        return _UT_FtqPdMem.DutUnifiedBase_CheckPoint(self, *args)

    def Restore(self, *args):
        return _UT_FtqPdMem.DutUnifiedBase_Restore(self, *args)

# Register DutUnifiedBase in _UT_FtqPdMem:
_UT_FtqPdMem.DutUnifiedBase_swigregister(DutUnifiedBase)

cvar = _UT_FtqPdMem.cvar

