.PHONY: build


_default: build


check_rtl:
	@files="../rtl/README.md ../rtl/README.md ../rtl/README.md" ; \
	for file in $$files; do \
		file=$$(realpath $$file); \
		if [ ! -f $$file ]; then \
			echo "Error: File '$$file' does not exist."; \
			exit 1; \
		fi; \
	done


build: check_rtl
	@echo "script $(MAKEFILE_LIST) is TBD"
