name: Run all test and generate report

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Set Up timezone
      uses: szenius/set-timezone@v2.0
      with:
        timezoneLinux: "Asia/Shanghai"

    - name: Checkout UnityChipForXiangShan
      uses: actions/checkout@v4

    - name: Check Commit
      run: |
        skip=false
        for ut in ut_backend ut_frontend ut_mem_block ut_misc; do
          if [ "$(git log -1 --format=%ct -- $ut)" -ne "0" ]; then
            echo "New commits found in $ut"
            skip=false
          else
            echo "No new commits in $ut"
          fi
        done
        echo "SKIP=$skip" >> $GITHUB_ENV
      shell: bash

    - name: Install dependencies
      if: env.SKIP == 'false'
      run: |
        pip3 uninstall -r requirements.txt -y
        pip3 install -r requirements.txt -y

    - name: Run tests and generate report
      if: env.SKIP == 'false'
      run: |
        make clean
        make CFG=configs/ci.yaml args="-n 32"

    - name: Checkout xs-mlvp.github.io repository
      if: env.SKIP == 'false'
      uses: actions/checkout@v4
      with:
        repository: 'XS-MLVP/xs-mlvp.github.io'
        token: ${{ secrets.WEB_PUSH_KEY }}
        path: 'xs-mlvp.github.io'

    - name: Configure git and sync
      if: env.SKIP == 'false'
      run: |
        cp -r out/report/* xs-mlvp.github.io/UnityChipForXiangShan/data/reports/
        cd xs-mlvp.github.io
        git config user.name "github-actions[bot]"
        git config user.email "22570332+github-actions[bot]@users.noreply.github.com"
        git add UnityChipForXiangShan/data/reports
        git commit -m reprort`date +%Y%m%d%H%M%S`
        git push
        echo "Sync complete"
